OpenKH/OpenKh

- README.md
- docs/index.md
- docs/kh2/builds.md
- docs/kh2/file-type.md
- docs/kh2/worlds.md
Touched up a few plaintext files. Primarily grammar and added missing information + expanded upon some already present information.
> Basic edits

- LICENSE
- README.md
As decided, I am installing the GPLv3 license.
> Install GPLv3 license

- OpenKh.Tools.BbsEventTableEditor/OpenKh.Tools.BbsEventTableEditor.csproj
- azure-pipelines.yml
I still have to see if this commits will fix an issue where all the OpenKh.Command.* tools are currently broken when downloaded from Azure Pipelines.
When it is going to be fixed, this PR can be reviewed.
> Attempt to fix broken command line tools

- OpenKh.Kh2/Objentry.cs
- OpenKh.Tools.ObjentryEditor/ViewModels/ObjentryViewModel.cs
This should fix the following bug https://github.com/Xeeynamo/OpenKh/issues/62
> Fix objentry names

- OpenKh.Tools.Common/Controls/DrawPanel.cs
This fixes https://github.com/Xeeynamo/OpenKh/issues/53
> Fix LayoutViewer bug

- ConsoleApp1/ConsoleApp1.csproj
- OpenKh.Tools.BarEditor/OpenKh.Tools.BarEditor.csproj
- OpenKh.Tools.BbsEventTableEditor/OpenKh.Tools.BbsEventTableEditor.csproj
- OpenKh.Tools.CtdEditor/OpenKh.Tools.CtdEditor.csproj
- OpenKh.Tools.DpdViewer/OpenKh.Tools.DpdViewer.csproj
- OpenKh.Tools.ImageViewer/OpenKh.Tools.ImageViewer.csproj
- OpenKh.Tools.Kh2SystemEditor/OpenKh.Tools.Kh2SystemEditor.csproj
- OpenKh.Tools.Kh2TextEditor/OpenKh.Tools.Kh2TextEditor.csproj
- OpenKh.Tools.LayoutViewer/OpenKh.Tools.LayoutViewer.csproj
- OpenKh.Tools.LevelUpEditor/OpenKh.Tools.LevelUpEditor.csproj
- OpenKh.Tools.ObjentryEditor/OpenKh.Tools.ObjentryEditor.csproj
- README.md
- azure-pipelines.yml
- pre-build.ps1
Now all the builds are distributed to GitHub Release.
This time all the tools are included.
There are some small improvements on versioning and DLL/EXE metadata too.
> Improve build automated system

- OpenKh.Tools.BarEditor/ViewModels/BarViewModel.cs
- This will avoid file corruption on saving, if user gives invalid index to bar entry.
> Add buffering to SaveCommand

- OpenKh.Imaging/ImageExtensions.cs
- OpenKh.Imaging/OpenKh.Imaging.csproj
- OpenKh.Imaging/PixelFormatExtensions.cs
- OpenKh.Tools.Common/ImageHelpers.cs
- OpenKh.Tools.Common/Imaging/GdiFormats.cs
- OpenKh.Tools.Common/Imaging/GdiImage.cs
- OpenKh.Tools.Common/Imaging/ImageExtensions.cs
- OpenKh.Tools.Common/Imaging/PixelFormatExtensions.cs
- OpenKh.Tools.Common/OpenKh.Tools.Common.csproj
- OpenKh.Tools.ImageViewer/Services/ImageFormatService.cs
This fixes a problem mentioned by @Soraiko in the Discord server: https://discord.com/channels/409140906625728532/567065170879184910/711318770735382529
> Decoupling GDI specific logic from OpenKH low level libraries

- docs/recom/World.md
Alternate World Tags from ReCoM
> Alt. World Tags

- docs/kh3/worlds.md
> Fixed typo of Radiant

- docs/kh3/updates.md
Some small updates for the editions and updates document
> Update KH3 patches

- OpenKh.Engine/Parsers/Kddf2/VU1Simulation.cs
- OpenKh.Game/Infrastructure/ArchiveManager.cs
- OpenKh.Game/States/MapState.cs
This fixes a couple of bugs that prevent some 3D models to be loaded correctly. This patch will allow to load all of them, regardless their "type".
> Fix model load

- OpenKh.Game/MonoSpriteDrawing.cs
Small patch to fix slow down on map selector debug menu.
> Set SetData buffer size to minimized.

- docs/index.md
- docs/remasters/15plus25/index.md
- docs/remasters/15plus25/updates.md
- docs/remasters/28fcp/index.md
- docs/remasters/28fcp/updates.md
> PS4 remasters Editions and Updates

- docs/bbs/bbsa.md
- docs/bbs/ctd.md
- docs/bbs/font.md
- docs/bbs/pam.md
- docs/index.md
- docs/kh1/file-type.md
- docs/kh1/worlds.md
- docs/kh2/file-type.md
- docs/kh2/file/type/00objentry.md
- docs/kh2/file/type/msg.md
Fixed some wrong link ID's, added navigation to KH1 and some pages were missing a link to the games index page. Do we want a link from game index page to the main index page?
> Doc: Fix links + add navigation to KH1

- OpenKh.Game/Config.cs
- OpenKh.Game/Global.cs
- OpenKh.Game/Infrastructure/Kernel.cs
- OpenKh.Game/OpenKh.Game.csproj
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/Program.cs
Since it was asked by many of you.
For most of the configuration parameters, they will affect the game in real time as soon as you save the change.
The configuration also adds `enforceInternationalTextEncoding`, which enables compatibility with unofficial KH2FM translations.
> Add game configuration

- OpenKh.Engine/Renders/ISpriteDrawing.cs
- OpenKh.Engine/Renders/Kh2MessageRenderer.cs
- OpenKh.Tools.Common/Rendering/SpriteDrawingDirect3D.Drawing.cs
> Fix new line for KH2 Text Editor

- OpenKh.Tools.LayoutEditor/Controls/ImSequencer.cs
> Fix bug where buttons input was overlapping

- OpenKh.Engine/Renders/LayoutRenderer.cs
- OpenKh.Engine/Renders/SequenceRenderer.cs
- OpenKh.Game/Infrastructure/Input/GamepadInput.cs
- OpenKh.Game/Infrastructure/Input/IInputDevice.cs
- OpenKh.Game/Infrastructure/Input/KeyboardInput.cs
- OpenKh.Game/Infrastructure/InputManager.cs
- OpenKh.Game/Infrastructure/Kernel.cs
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/States/MapState.cs
- OpenKh.Game/States/Title/AnimatedSequenceRenderer.cs
- OpenKh.Game/States/Title/Constants.cs
- OpenKh.Game/States/Title/ITitleMainMenu.cs
- OpenKh.Game/States/Title/ITitleSubMenu.cs
- OpenKh.Game/States/Title/NewGameMenu.cs
- OpenKh.Game/States/Title/TitleLayout.cs
- OpenKh.Game/States/Title/TitleState.cs
- OpenKh.Game/States/TitleState.cs
Very basic, but accurate implementation of the "New Game" menu in the title screen.
This aims to define the fundamentals of in-game menu creation and the extension of the title screen.
> Game title menu

- OpenKh.Tools.ObjentryEditor/ViewModels/ObjentryViewModel.cs
- OpenKh.Tools.ObjentryEditor/Views/ObjentryView.xaml
This adds the possibility to remove sub-spawns from an object.
> KH2 Objentry Editor: Add way to clear "Spawn object X"

- OpenKh.Engine/Renders/SequenceRenderer.cs
- OpenKh.Tools.LayoutEditor/Controls/MySequencer.cs
This PR covers the fix of additional bugs and glitches found after #184
> More Layout Editor fixes

- OpenKh.Engine/Renders/SequenceRenderer.cs
- OpenKh.Game/States/Title/AnimatedSequenceRenderer.cs
- OpenKh.Game/States/Title/ITitleMainMenu.cs
- OpenKh.Game/States/Title/NewGameMenu.cs
- OpenKh.Game/States/Title/TitleState.cs
- OpenKh.Kh2/Sequence.cs
- OpenKh.Tools.LayoutEditor/AppSequenceEditor.cs
- OpenKh.Tools.LayoutEditor/Dialogs/SpriteGroupEditDialog.cs
- OpenKh.Tools.LayoutEditor/Models/SpriteGroupModel.cs
Adds those SEQD values that are responsible to attach a portion of text in the UI. There is still no way to preview the text in the Layout Editor, but at least it shows the proper labels.
I fixed a scaling rendering issue when the pivot was different than (0, 0) and I improved the GUI here and there (eg. the checkbox "Do not loop" is now called "Loop animation" and the logic of the check is inverted, etc. )
I am asking to review those changes and merge because I do not plan to continue to work on the Layout Editor again soon as I want to move to other aspects of KH2 engine for a while.
EDIT: Oh, those SEQD text stuff is now implemented also in the game engine! There are some very minor issues with the English version, but the Japanese version looks perfect.
> Sequence improvements

- ConsoleApp1/ConsoleApp1.csproj
- OpenKh.Bbs/Event.cs
- OpenKh.Bbs/OpenKh.Bbs.csproj
- OpenKh.Command.ImgTool/OpenKh.Command.ImgTool.csproj
- OpenKh.Command.Layout/OpenKh.Command.Layout.csproj
- OpenKh.Common/Archives/HdAsset.cs
- OpenKh.Common/OpenKh.Common.csproj
- OpenKh.Kh2/BaseTable.cs
- OpenKh.Kh2/Battle/BaseBattle.cs
- OpenKh.Kh2/Battle/Vtbl.cs
- OpenKh.Kh2/Jiminy/BaseJiminy.cs
- OpenKh.Kh2/Mixdata/BaseMixdata.cs
- OpenKh.Kh2/OpenKh.Kh2.csproj
- OpenKh.Kh2/System/BaseSystem.cs
- OpenKh.Kh2/System/Ftst.cs
- OpenKh.Kh2/System/Item.cs
- OpenKh.Tests/OpenKh.Tests.csproj
- OpenKh.Tests/kh2/BattleTests.cs
- OpenKh.Tools.Kh2SystemEditor/OpenKh.Tools.Kh2SystemEditor.csproj
- OpenKh.Tools.Kh2TextEditor/OpenKh.Tools.Kh2TextEditor.csproj
I noticed that few NuGet packages were behind and that some tools had inconsistency across the versions. This just updates all the NuGet packages and does not bring any functional changes to the project. Some bugfixes from those NuGet packages might be included.
> Upgrade all NuGet packages

- docs/kh2/file/type/coct.md
Update COCT flags documentation reflecting research result from Disgustor!
(and some markdown tweaks)
> Update COCT flags doc.

- docs/kh1/file-type.md
the .dpp file from what I've seen is simply the header that can be attached to the start of it's corresponding dpx file
> Update on ".dpp" file

- OpenKh.Tools.Kh2BattleEditor/ViewModels/BonsViewModel.cs
- OpenKh.Tools.Kh2BattleEditor/ViewModels/EnmpViewModel.cs
- OpenKh.Tools.Kh2BattleEditor/ViewModels/FmlvViewModel.cs
- OpenKh.Tools.Kh2BattleEditor/ViewModels/LvupViewModel.cs
- OpenKh.Tools.Kh2BattleEditor/ViewModels/PrztViewModel.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/ItemViewModel.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/TrsrViewModel.cs
Fixes this issue: 
https://discordapp.com/channels/409140906625728532/567061704849096725/743445793951842355
> Save the unfiltered list when searching items

- docs/kh2/file/model.md
- docs/kh2/file/raw-texture.md
PS. my collection of [ksy](https://kaitai.io/) and [bt](https://www.sweetscape.com/010editor/templates.html) is found at: https://gitlab.com/kenjiuno/khkh_xldM/-/tree/master/Parser
> Some updates for UVSC and TEXA.

- OpenKh.Command.MapGen/Utils/CollisionBuilder.cs
- OpenKh.Kh2/Coct.cs
Integration of Kenjiuno's fix for #224
> Collision optimization fix

- OpenKh.Tools.Kh2SystemEditor/OpenKh.Tools.Kh2SystemEditor.csproj
- OpenKh.Tools.Kh2SystemEditor/Utils/DictListWriteUtil.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/SystemEditorViewModel.cs
[EPPlus 5](https://github.com/EPPlusSoftware/EPPlus) is completely rewritten from scratch for proprietary use, and its license is not compatible with Apache-2.0 License.
Replace EPPlus 5 with [NPOI](https://github.com/tonyqus/npoi) using Apache-2.0 License.
> Replace EPPlus with NPOI

- OpenKh.Kh2/Bar.cs
- OpenKh.Tools.BarEditor/ViewModels/BarViewModel.cs
- OpenKh.Tools.BarEditor/Views/BarView.xaml
See: https://discord.com/channels/409140906625728532/575294743852875787/738043289944457226
> Support editing of bar file's flag in BarEditor

- docs/kh2/dictionary/characters.md
- docs/kh2/file/type/00battle.md
- docs/kh2/index.md
Ordered the 00Battle subfiles.
Addded specifics on each subfile's structure.
Added/Updated missing info on most subfiles.
Added the characters dictionary (Used on 00battle)
Added a "Dictionaries" section to the index for easy access.
> 00battle update + dictionary access

- docs/kh2/file/type/03system.md
Ordered the subfiles, added some missing information, including the whole shop  subfile,  and added the structure section on subfiles that didn't have them.
> 03System update

- OpenKh.Engine/Parsers/Kddf2/Kkdf2MdlxParser.cs
- OpenKh.Engine/Parsers/Kddf2/VU1Simulation.cs
- OpenKh.Engine/Renders/SequenceRenderer.cs
- OpenKh.Kh2/Sequence.cs
- OpenKh.Tests.Engine/AnimatedSequenceFactoryTests.cs
- OpenKh.Tools.LayoutEditor/App.cs
- OpenKh.Tools.LayoutEditor/AppLayoutEditor.cs
- OpenKh.Tools.LayoutEditor/AppSequenceEditor.cs
- OpenKh.Tools.LayoutEditor/Controls/MySequencer.cs
- OpenKh.Tools.LayoutEditor/Dialogs/SpriteGroupEditDialog.cs
- OpenKh.Tools.LayoutEditor/Interfaces/IEditorSettings.cs
- OpenKh.Tools.LayoutEditor/Models/SpriteGroupModel.cs
- OpenKh.Tools.LayoutEditor/Settings.Designer.cs
- OpenKh.Tools.LayoutEditor/Settings.settings
This is based from [@Vladabdf suggestions](https://discordapp.com/channels/409140906625728532/575294743852875787/751213000538456204). I do not know if I will be able to implement everything in a reasonable amount of time, but most of them are definitively good quality improvements.
A big note to the "Attach text": that is not actually only for text, but also for animations. Please look the commit messages to know which changes will be performed during the development of this PR.
> Layout Editor improvements

- OpenKh.Kh2/Ard/SpawnPoint.cs
> Fix 285: out of bound Spawn points bug

- docs/kh2/file/type/mset.md
- docs/kh2/index.md
MSET effects documentation (And later animations too if somebody knows the structure). I haven't tested the effects myself, they are from Soraiko's doc.
> MSET effects doc

- docs/kh1/file-type.md
.evm is a series of multiple msets appended to each other that are used in cutscenes. They have the room name that they're used in the file name, ie "tw01"
> adds evm description

- OpenKh.Engine/Motion/IModelMotion.cs
- OpenKh.Engine/Motion/Kh2MotionEngine.cs
- OpenKh.Engine/Parsers/MdlxParser.cs
Draft pull request with some ideas on how to implement animations in-game. It is far from being done and I have very little knowledge on how to do it.
The core animation mechanic is found in `Kh2MotionEngine.ApplyInterpolatedMotion`. I copied the code from `MdlxParser.BuildTPoseMatrices` and expanded it as an attempt to try to create an animation. But the pose looks very messy at the moment.
The branch there will be useful to mess around and try to understand how animation works in-game and to replicate them in-engine.
> Interpolated animation support in-engine

- OpenKh.Tools.Kh2TextEditor/OpenKh.Tools.Kh2TextEditor.csproj
- OpenKh.Tools.Kh2TextEditor/ViewModels/TextEditorViewModel.cs
- OpenKh.Tools.Kh2TextEditor/Views/TextEditorView.xaml
- OpenKh.Tools.Kh2TextEditor/Views/TextEditorView.xaml.cs
Made many additions, such as:
-> Add a new line when RETURN is pressed.
-> Ability to add strings [Adds a "FAKE"].
-> Ability to remove strings [Revomes selected].
-> A context menu for the TextBox for adding Commands and Icons.
-> A ColorBox for the Color Command.
Demo Images:
Known Bugs:
-> Every function that adds to the text causes the Cursor to return to 0. This cannot be negated for now because of the MVVM arrangement.
-> Icon View is broken but that is not because of my changes.
-> Code is a bit ugly, but that can be fixed.
Planned Changes:
-> Fix [fontimage/icon] unswizzling
-> Make a "better" Icons context menu.
IMPORTANT:
The ColorBoxDialog is from https://github.com/drogoganor/ColorPickerWPF which is included as a NuGet package.
> Many additions to KH2TextEditor

- docs/bbs/bcd.md
- docs/bbs/index.md
- docs/bbs/maps.md
- docs/bbs/pmo.md
- docs/bbs/pmp.md
Adds documentation for BBS's models, maps and what's known of the map's collision data.
> Documents  bbs models, maps and collisions

- OpenKh.Tools.Common/MessageDialog.xaml
- OpenKh.Tools.Common/MessageDialog.xaml.cs
- OpenKh.Tools.Common/OpenKh.Tools.Common.csproj
- OpenKh.Tools.ImageViewer/ViewModels/ImageViewerViewModel.cs
- OpenKh.Tools.ImageViewer/Views/MainWindow.xaml
Addresses issue #331. The requested method implements a new Dialog class to OpenKh.Tools.Common to make use of.
A re-run of #343 without edits to Xe.Tools.Wpf
Image:
> Add a dialog to inform missing PngQuant on ImageViewer.

- OpenKh.Command.IdxImg/Program.cs
Does what the title says. Seeks out the LBA Offset of the IDX and IMG from the ISO.
This is hacky, but as far as I have seen, it works with everything tested.
Addresses #348.
Tested ISOs:
-> KH2US
-> KH2FM
-> KH2CCZ
Of course, more testing is necessary. But this will do until we have a proper ISO library.
> Somewhat hacky but effective way to implement IDX/IMG LBA Seek.

- docs/kh2/file/type/00battle.md
> Limt update

- docs/kh2/file/type/mixdata.md
Completed Reci and Cond. Added mat exp on Exp.
> Docs - Mixdata file update

- docs/khds/days/index.md
- docs/khds/days/worlds.md
My very first, small, pull request.
> Add world list for KH Days

- .github/workflows/auto-merge.yml
As they are pretty chatty and annoying, I suggest to auto-merge them. Example of them are #363 and #364 .
> Automatically merge PR from Dependabot

- docs/kh2/dictionary/characters.md
- docs/kh2/file/type/00objentry.md
- docs/kh2/file/type/03system.md
Added the Sklt file. Added the structure of Arif and Evtp files.
> Sklt, Arif and Evtp files

- OpenKh.Game/Infrastructure/Kh2Field.cs
- OpenKh.Kh2/Ard/SpawnPoint.cs
- OpenKh.Tools.Common.CustomImGui/ImGuiEx.cs
- OpenKh.Tools.Kh2MapStudio/Windows/SpawnPointWindow.cs
- docs/kh2/file/type/areadata.md
Updates map studio and the documentation with the new discovered fields.
> AreaData further fields research

- docs/kh2/file/type/00battle.md
I have no idea of the file type for the unknowns. Also, offsets written are in hex (it's still very inconsistent even within this file).
> Added info for Btlv.

- docs/kh2/file/type/00battle.md
- docs/kh2/file/type/03system.md
- docs/kh2/file/type/preferences.md
Added the data for the Preferences' files. Moved to a new page because there was a lot of data.
> Prefs files

- .github/ISSUE_TEMPLATE/bug_report.md
> Bug Report Template

- OpenKh.Game/Debugging/DebugOverlay.cs
- OpenKh.Game/Debugging/IDebug.cs
- OpenKh.Game/Debugging/IDebugConsumer.cs
- OpenKh.Game/Debugging/Log.cs
- OpenKh.Game/Infrastructure/Input/GamepadInput.cs
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/States/IState.cs
- OpenKh.Game/States/MapState.cs
- OpenKh.Game/States/MenuState.cs
- OpenKh.Game/States/Title/TitleState.cs
> Clean-up of some dead code

- docs/ddd/worlds.md
As the title says, a compehensive list of all maps and worlds that exist or existed in Dream Drop Distance.
> Full list of maps in Dream Drop Distance

- docs/kh3/pawns.md
These are the Enemy pawns from the LimitCut Episode.
> LimitCut Pawns

- CONTRIBUTING.md
- DOCS_GUIDELINE.md
Draft to discuss the documentation guidelines to follow when contributing new documentation to the project.
> Documentation Guidelines

- OpenKh.Tools.Common/MessageDialog.xaml.cs
> Fix crash when clicking pngquant download link

- OpenKh.Engine/Renders/SequenceRenderer.cs
- OpenKh.Tools.LayoutEditor/Controls/ImSequencer.cs
> Fix crash when deleting all layers in the Layout Editor

- OpenKh.Tools.IdxImg/ExtractProcessor.cs
- OpenKh.Tools.IdxImg/Interfaces/IExtractProgress.cs
- OpenKh.Tools.IdxImg/ViewModels/EntryParserModel.cs
- OpenKh.Tools.IdxImg/ViewModels/EntryViewModel.cs
- OpenKh.Tools.IdxImg/ViewModels/FileViewModel.cs
- OpenKh.Tools.IdxImg/ViewModels/FolderViewModel.cs
- OpenKh.Tools.IdxImg/ViewModels/IdxViewModel.cs
- OpenKh.Tools.IdxImg/ViewModels/RootViewModel.cs
- OpenKh.Tools.IdxImg/Views/ExtractProgressWindow.xaml
- OpenKh.Tools.IdxImg/Views/ExtractProgressWindow.xaml.cs
fancy :))) #435 📈
PS. You can now cancel the extraction process by closing the loading window
> Extract 000xx.idx from the UI + loading screen

- OpenKh.Tools.ImageViewer/Views/MainWindow.xaml
- OpenKh.Tools.ImageViewer/Views/MainWindow.xaml.cs
Self explanatory. Requested by @Vladabdf.
> Add Drag n' Drop Support to OpenKh.Tools.ImageViewer

- OpenKh.WinShell.IMDUtilities/IMDThumbnail.cs
- OpenKh.WinShell.IMDUtilities/OpenKh.WinShell.IMDUtilities.csproj
- OpenKh.WinShell.IMZUtilities/IMZExtract.cs
- OpenKh.WinShell.IMZUtilities/IMZRepack.cs
- OpenKh.WinShell.IMZUtilities/OpenKh.WinShell.IMZUtilities.csproj
For some reason, fixes #430.
Needs testing on other machines to confirm.
> Fix invalid file usage for WinShell programs.

- docs/ddd/file/lboard.md
- docs/ddd/index.md
Documentation for the lboard.bin file located in the "game.rbin" of DDD.
> Ddd lboard

- OpenKh.Game/Infrastructure/InputKeyboard.cs
- OpenKh.Game/States/MapState.cs
- OpenKh.Tools.Kh2MapStudio/App.cs
Fix inverted controls in both OpenKh.Game and OpenKh.Tools.MapStudio
> Fix inverted character controls

- OpenKh.Tools.Kh2MapStudio/App.cs
- OpenKh.Tools.Kh2MapStudio/MapRenderer.cs
Please refer to the list of commits to know what bugs have been fixed.
> Fix various minor issues with MapStudio

- OpenKh.Kh2/Ard/SpawnPoint.cs
- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tests/Patcher/PatcherTests.cs
Spawnpoint method for the mod manager. It would be nice to be able to provide partial yaml file and mege it into the existing spawnpoint, but I wanted to get this out first since functionally that would just be an improvement.
Example mod using this method: https://github.com/thundrio-kh/kh2-spawnpoint-example
> spawnpoint method

- docs/kh2/file/type/msn.md
> KH2: MSN documentation

- docs/mom/abilities.md
- docs/mom/characters.md
- docs/mom/database.md
- docs/mom/index.md
- docs/mom/sed.md
- docs/mom/tracks.md
Hi! I've updated the documentation for Melody of Memories with smaller markdown changes and a new page for the track list. Hope this can be merged into the main docs. Cheers!
> Updated MOM docs

- docs/kh2/file/type/areadata.md
- docs/kh2/file/type/libretto.md
Still a lot of unknown, but probably better than nothing
> ARD Update & Libretto Documentation

- OpenKh.Bbs/Bbsa.Entry.cs
- OpenKh.Bbs/Bbsa.Names.cs
- OpenKh.Bbs/Bbsa.Partition.cs
- OpenKh.Bbs/Bbsa.cs
- OpenKh.Command.Bbsa/Program.cs
Not all optimized, but works for repacking all .DAT partitions with respective files ordering.
> *Repack algorithm added

- docs/kh3/battlequotes.md
- docs/kh3/index.md
Ok, this one might be a bit special, but as it's coming up every once in a while for character mods, I thought it might as well be documented here. For now the page only lists Sora.
> [Docs] KH3 Battle Quotes

- docs/kh2/dictionary/obj.md
Changed B_EX200 description in obj from (?) Piramid shape? Related to Xemnas? to (B) Twilight Thorns Energy Ball (Break Raid RC)
> Fixed B_EX200 obj description

- docs/kh2/file/type/image.md
Fixed a couple of descriptors for IMGD header information
> Imgd correction

- docs/kh2/file/type/image.md
Clarified how to calculate the desired value, as it may not be intrinsically clear.
> Add comment to IMGD header

- docs/kh3/battlequotes.md
Xemnas transcription by VaultLink. + fixed a line by TX
> Added Xemnas

- docs/kh2/index.md
- docs/kh2/notable-files.md
- docs/kh2/unused.md
Apologies for sending so many pull requests.
> Added missing index file and attempted to fix "unused.md" table

- OpenKh.Egs/EgsTools.cs
As the title suggests, I was able to figure out the correct method for getting the offsets needed to correctly link HD textures to *.map files.
Useful for anyone editing or creating new maps for the PC port of KH2.
> Support for map HD asset linking

- docs/kh1/dictionary/mdls.md
Hiya, apologies for the original model entry mistakes, my bad, I went back and adjusted stuff. Things like heartless names, etc should be appearing correctly now.
> .mdls model entries corrections

- OpenKh.Command.HdAssets/OpenKh.Command.HdAssets.csproj
- OpenKh.Command.HdAssets/Program.cs
- OpenKh.Egs/EgsTools.cs
- OpenKh.Egs/Helpers.cs
Gave OpenKh.Command.HdAssets a new option "scan" for scanning a file or a folder of files to give some info on how many assets are inside for hd linking.
> New scan option for HdAssets

- OpenKh.Imaging/PngImage.cs
#607 did not fix it for all the scenario. This implementation is a bit inefficient but should do the trick...
> PngImage fix for .NET 6

- OpenKh.Game/Config.cs
- OpenKh.Game/Entities/ObjectEntity.cs
Not sure how and why this went unnoticed for a year
> Fix OpenKH Game crash at start-up

- OpenKh.Egs/EgsHdAsset.cs
> Fix EGS asset extraction

- docs/kh2/file/type/03system.md
I recently took apart and learned a bit more about the SHOP format so I added what I learned and corrected some bits of info.
> Adding some corrections about the SHOP file.

- OpenKh.Patcher/SourceAssets.cs
- OpenKh.Research.Panacea/OpenKh.Research.Panacea.vcxproj
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
Should allow the wizard to proceed where it was previously getting stuck.
> Update game data found detection for EGS version

- OpenKh.Egs/EgsTools.cs
- OpenKh.Patcher/Metadata.cs
- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tools.ModsManager/OpenKh.Tools.ModsManager.csproj
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
_"Yes, patching is outside of the scope of OpenKH, but discrimination is too, so it will be merged as long as it works and is received well. And we prioritize function, user accessibility, and friendliness even above our functionality standards."_
After some private discussion with some of the other collaborators, I decided to re-open this PR from scratch to hopefully finally make it in. I will just copy and paste my statement from the PR prior:
Build_From_MM was a Python program used which allowed for Mod Manager mods to be used in the PC ports.
This PR basically takes in everything it can do and implements it to Mod Manager itself so that we don't have to fiddle around with some other executable and basically have the Mod Manager do everything on it's own.
What it does:
- Allowing the …
> Improve the Mod Manager for PC Modding Experience.

- OpenKh.Research.Panacea/Panacea.cpp
> Fix loading remastered asset replacement when original file is not replaced.

- .github/workflows/codeql.yml
- .github/workflows/dotnet.yml
- OpenKh.Egs/EgsTools.cs
- OpenKh.Patcher/Metadata.cs
- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tools.ModsManager/OpenKh.Tools.ModsManager.csproj
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
- OpenKh.sln
- build.sh
- Panacea installation should work, as long as you have `OpenKh.Panacea.dll` in the right place (the automated build scripts probably still need some work to automate this)
- Panacea is marked as experimental and is an optional install if you prefer patching over the mod loading. If we want to remove the Experimental from the name, happy to make that change, or we could make it when merging to master.
> Bring master branch changes into mods loader branch

- OpenKh.Research.Panacea/OpenKH.cpp
- OpenKh.Research.Panacea/OpenKH.h
- OpenKh.Research.Panacea/Panacea.cpp
- OpenKh.Research.Panacea/Panacea.h
This allows the mod folder to be placed in a directory containing Unicode characters.
> Adding Unicode support to Panacea.

- OpenKh.Tools.ModsManager/Services/WizardPageStackService.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
Implement page stack and page back for ModsManager wizard
https://user-images.githubusercontent.com/5955540/190887720-753197dc-7dc9-4c85-bb54-45ff283307ce.mp4
Fix #675
> Implement page stack and page back for ModsManager wizard

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
If they have a valid shortcut to the KH launcher to speed up playing slightly.  Merged in a very roundabout way but took Kenjiunos code and readded my stuff
> Allowed PC to Build and Run or Run only

- OpenKh.Research.Panacea/OpenKH.cpp
- OpenKh.Research.Panacea/OpenKH.h
- OpenKh.Research.Panacea/Panacea.cpp
Works with mod manager updates in #696.
> Implementing multi-game support for Panacea.

- .github/workflows/dotnet.yml
> Fix copy error of panacea

- OpenKh.Command.Bdxio/Models/BdxHeader.cs
- build.ps1
> Try to fix auto released `openkh.zip` only contains panacea dll

- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/ModDetailsView.xaml
To easier see if someone is asking for help what version Openkh mod manager GameEdition is. "PC Version" or "Emulator"
> Made a menu item to show if openkh is configured for PC or Emulator

- docs/kh2/file/type/areadata.md
Added explanations to unk1d, unk06, and unk07
> ARD doc update

- OpenKh.Kh2/Battle/Atkp.cs
- OpenKh.Kh2/SystemData/Sklt.cs
- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tests/Patcher/PatcherTests.cs
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- docs/tool/GUI.ModsManager/index.md
Adds the ability to listpatch the sklt subfile in system.bin
> Addeed sklt to ListPatch with documentation and a test.

- OpenKh.Command.Bdxio/Utils/BdxDecoder.cs
- OpenKh.Command.Bdxio/Utils/BdxTrigger.cs
- OpenKh.Tests.Commands/res/bdx/t01/b.bdscript
https://discord.com/channels/409140906625728532/567065170879184910/1073082835868598333
An output sample:
```
---
WorkSize: 128
StackSize: 512
TempSize: 512
Triggers:
- Key: 17
Addr: OBJ_ANMATR_CALLBACK
- Key: 23
Addr: LIMIT_CALL
- Key: 22
Addr: LIMIT_START
Name: limitform
---
...
```
> Resolve known trigger names

- OpenKh.Kh2/ObjectCollision.cs
- OpenKh.Tools.Kh2MdlxEditor/Utils/EnumPairingUtils.cs
- OpenKh.Tools.Kh2MdlxEditor/ValueConverters/EnumDisplayConverter.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/CollisionProperties_Control.xaml
- OpenKh.Tools.Kh2MdlxEditor/Views/CollisionProperties_Control.xaml.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/CollisionV_Control.xaml
> Adding TypeEnum and ShapeEnum

- .github/workflows/dotnet.yml
- OpenKh.Tools.ModsManager/OpenKh.Tools.ModsManager.csproj
- OpenKh.Tools.ModsManager/Services/OpenkhUpdateCheckerService.cs
- OpenKh.Tools.ModsManager/Services/OpenkhUpdateProceederService.cs
- OpenKh.Tools.ModsManager/Services/ProgressWindowService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/WorkInProgressWindow.xaml
- OpenKh.Tools.ModsManager/Views/WorkInProgressWindow.xaml.cs
> Implement downloader and updater on client side

- OpenKh.Tools.Kh2MsetEditor/Views/Motion_Control.xaml
> [KH2MsetEditor] Add ability to view/edit Bounding Box Min/Max within an msets anb

- docs/kh1/worlds.md
Added World Location Area names: 
Credit should largely go to Murugo for his Kingdom Hearts Map Viewer 0.1.5 program clearly listing the location names of the ,bin files, I just compiled it into a list for openkh :)
> Add to worlds.md

- OpenKh.Tools.Kh2MapStudio/App.cs
When clicking map name
This will be popped up if it appears to be clear that there are 2 or more ard files set.
Fix #836
> Adding ard file selector

- CODE_GUIDELINE.md
- CONTRIBUTING.md
- OpenKh.Game/Program.cs
- README.md
- pre-build.ps1
Fixed redirects all throughout the code that led to Xeeynamo's copy of the repository. Additionally made a broader credit to OpenKH as a whole in the "About" dialog.
> Some text corrections

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
When checked/true Mod Manager will update all installed mods on startup if there are any updates found.
> Auto Update toggle added to info menu in Mod Manager.

- .github/workflows/dotnet.yml
Update dotnet.yml with suggested xcopy
> Panacea Dependency fix

- OpenKh.Tools.LayoutEditor/Dialogs/SpriteEditDialog.cs
> Try to fix #877

- OpenKh.Research.Panacea/OpenKh.Research.Panacea.vcxproj
- OpenKh.Research.Panacea/dllmain.cpp
> Allow Panacea to load all DLLs from a subfolder.

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
This goes with #892 merge that first then this
> Panacea dependency subfolder stuff

- OpenKh.Tools.ModsManager/Services/ModsService.cs
> Fix OpenKH freezing when pulling from a Github Repo.

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
I forgot Mod Loader is true with panacea installed or !PC
> Fix panacea settings showing if you setup for emulator.

- OpenKh.Tools.KhModels/KIH2/MapProcessor.cs
> KhModels - Fix KH2 maps UV

- OpenKh.Bbs/Ctd.cs
- OpenKh.Bbs/Messages/Internals/InternationalCtdEncoder.cs
- OpenKh.Engine/Renders/ISpriteDrawing.cs
- OpenKh.Tests/Bbs/CtdTests.cs
- OpenKh.Tools.CtdEditor/App.xaml.cs
- OpenKh.Tools.CtdEditor/Interfaces/CtdDrawHandler.cs
- OpenKh.Tools.CtdEditor/Interfaces/IDrawHandler.cs
- OpenKh.Tools.CtdEditor/ViewModels/CtdViewModel.cs
- OpenKh.Tools.CtdEditor/ViewModels/FontEditorViewModel.cs
- OpenKh.Tools.CtdEditor/ViewModels/LayoutEditorViewModel.cs
- OpenKh.Tools.CtdEditor/ViewModels/MainViewModel.cs
- OpenKh.Tools.CtdEditor/ViewModels/MessageViewModel.cs
- OpenKh.Tools.CtdEditor/Views/CtdView.xaml
- OpenKh.Tools.CtdEditor/Views/LayoutWindow.xaml
- OpenKh.Tools.CtdEditor/Views/LayoutWindow.xaml.cs
- OpenKh.Tools.CtdEditor/Views/MainWindow.xaml
* Ctd Editor renders text again
* You can now see/edit layouts
The CtdEncoder is still missing some special chars, how the text layout works needs more investigation, and you can't change the font used for rendering yet, but I want to get this in peoples hands before I go off down another rabbit hole...
> Ctd Editor improvements: round 1

- OpenKh.Tools.ModsManager/Services/ColorThemeService.cs
- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/ModDetailsView.xaml
- OpenKh.Tools.ModsManager/Views/ModManagerView.xaml
- OpenKh.Tools.ModsManager/Views/PresetsWindow.xaml
- OpenKh.Tools.ModsManager/Views/PresetsWindow.xaml.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
Thanks to @kenjiuno he made a proper ColorThemeService.cs and told me how to implement it in the colors I had previously hardcoded.
> Dark Mode Toggle

- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml.cs
and other crash prevention/fixes i forgot
> support for dddpcpatch.

- OpenKh.Tools.Kh2MapStudio/App.cs
- OpenKh.Tools.Kh2MapStudio/EditorSettings.cs
- OpenKh.Tools.Kh2MapStudio/Settings.Designer.cs
- OpenKh.Tools.Kh2MapStudio/Settings.settings
Currently event script section is always visible.
Now event script can be hidden, hidden by default.
> Add option to show/hide Event script section

- OpenKh.Kh2/Models/ModelCommon.cs
Simplified the GetBonesMatrices method.
NOTE: (Disregarding the old code that was taking it into account too.)
In a general mathematic context, computing matrices require a **recursive** complexity code, the **linear** complexity code above is possible because a rule shared by most model skeletons says that a relative matrix is always defined before its children matrices. 
Simplification does not always rhyme with reliability, but it did here. Previous code has a != comparison with two Singles, and the unnecessary use of Quaternion and Vector3 (Considering they're not reused later for loss reasons, this method is not meaning it either.) I made sure my modification was not just giving an illusion of success by setting random SRT values for bones, witnessing the graphical change with a tool …
> Simplification of GetBonesMatrices Method.

- OpenKh.Kh2/Models/ModelCommon.cs
- OpenKh.Tools.Kh2MdlxEditor/Utils/MdlxEditorImporter.cs
Changed the decompose function based on Assimp's. It now generates correct equal euler angles. Ingame some animations break if the whole skeleton is imported, the reason is unknown.
Bone bitflags have also been updated, they were incorrect.
> MdlxEditor - Skeleton decompose update

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
and random whitespace cleanup. (trying a new plugin that automatically trims whitespace when I save a file
> Fix unable to extract due to hardcoded gameDataLocation

- docs/kh3/battlequotes.md
- docs/kh3/worlds.md
I added `battlequotes.md` documentation for Aqua and Riku (the two other characters in the player characters folder). I also updated a couple of the worlds in `worlds.md`.
> Updated documentation for battlequotes and worlds

- docs/tool/GUI.ModsManager/FAQ.md
Will just force merge with master, as this does not alter any tool code and is relevant only to documentation
> Correct new FAQ page for the website (hopefully)

- OpenKh.Bbs/OpenKh.Bbs.csproj
- OpenKh.Bbs/Pmp.cs
- OpenKh.Patcher/OpenKh.Patcher.csproj
- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tests/Patcher/PatcherTests.cs
- docs/tool/GUI.ModsManager/creatingMods.md
Adds "bbsarc" as a valid mode in mod.ymls. Should work just like binarc.
> Add "bbsarc" patch mode

- docs/tool/GUI.ModsManager/creatingMods.md
> [Docs] Fixes regression to Table of Contents, adds FMAB example

- OpenKh.Tools.ModsManager/Views/ModManagerView.xaml
After fix
Dark mode
Light mode
> Fix foreground color of checkbox inside list of installed mods.

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
Adds UI to Enable/Disable logging souund effects
> New Panacea Sound Debug Setting

- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
for users who increase text size through accessibility options.
> Add ScrollViewer to each setup wizard window 

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
Fix Mod Manager setup wizard showing SteamAPI trick page on non steam versions after updating OpenKh
> Mod Manager Bug Fix

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
being unable to be created on first time setup and unable to be deleted (when trying to delete and error/crash would happen)
> Fix panacea_settings.txt

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
if file is being used by another program with exclusive access or if it doesnt exist etc
> More try catch to prevent setup wizard from crashing.

- docs/kh2/file/type/03system.md
> Document Disable Form Bitflags.

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
since for the few people who do patch a small percent of them might have MM crash on them.
also removed a duplicate if statement in setup wizard
> Added a try catch to patching 

- OpenKh.Egs/EgsTools.cs
> [ModManager] Also apply the PAX fixes for the patcher

- OpenKh.Egs/EgsTools.cs
- OpenKh.Research.Panacea/Panacea.cpp
This addresses an edge case issue from the last PR where we would get an improper number of remastered assets required. Some DPD textures share this firstTwoBytes value, but don't have a shX or shY value which tells the game to shift the texture a number of units, which means these textures aren't intended to be combined. This PR makes sure textures pass both of these conditions before being combined.
> Additional Panacea/Patcher Pax Fixes

- OpenKh.Tools.ModsManager/App.xaml
- OpenKh.Tools.ModsManager/App.xaml.cs
- OpenKh.Tools.ModsManager/Converters/BooleanToVisibilityConverter.cs
- OpenKh.Tools.ModsManager/Converters/InverseBooleanConverter.cs
- OpenKh.Tools.ModsManager/Models/DownloadableModModel.cs
- OpenKh.Tools.ModsManager/Services/DownloadableModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/DownloadableModViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/ModManagerView.xaml
- OpenKh.Tools.ModsManager/Views/ModSearchWindow.xaml
- OpenKh.Tools.ModsManager/Views/ModSearchWindow.xaml.cs
This pull request adds a new Online Mods window to the ModsManager application, allowing users to browse, search, and install mods directly from repositories. It also implements real-time search functionality, enabling users to quickly filter downloadable mods by name, description, and author.
- Added a dedicated window for browsing and installing mods from online repositories
- Created UI components for displaying mod details, screenshots, and information
- Implemented asynchronous loading of mod data from repositories with proper progress indicators
- Added proper error handling and caching for offline access
- Implemented search box with magnifying glass icon and clear button
- Added live filtering against mod name, description, and author
- Preserved selection state during filtering …
> Add Online Mods Window with Real-time Search Functionality

- OpenKh.Kh2/Pax.cs
> Fix Kh2 PAX write element count
