- OpenKh.Kh2/Bar.cs
- OpenKh.Kh2/Contextes/FontContext.cs
- OpenKh.Kh2/Imgd.cs
- OpenKh.Kh2/Ps2.Utility.cs
- OpenKh.Kh2/RawBitmap.cs
- OpenKh.Tests/kh2/FontContextTests.cs
* Add RawBitmap support for 4 bit and 8 bit images
* Centralize in one point the loading of US and JP fonts
* Complete JP font support
* Spacing support
This will be very useful for the rendering support
> Add FontContext to handle KH2 fonts easily

- docs/kh2/file/type/bar.md
Excuse me in advance for this long PR and semi off-topic questions below, I tried to keep this as professional as possible.
* the type is only a uint16, it can contain a duplicate flag
* type 0x04 is not composed solely of VIF packets, albeit mostly, refer to my old tools for more details on their inner workings
* the zero value is a lookup address used at runtime
Keep in mind all of this was done through memory, so someone would have to double check this info i guess.
On another note don't you think something like a [kaitai](http://kaitai.io/) setup would be much more explicit for structures? That would allow you to get a parser for free on top of auto-generated docs ( I will avoid to start an argument about other technologies used by the project and only mention it can output C# )
Also …
> misc fixes on bar docs

- docs/kh1/file-type.md
- docs/kh1/index.md
- docs/kh1/worlds.md
- docs/kh2/file-type.md
Added Initial files for KH1 documentation with a similar format to the existing KH2 documentation.
Modified file-type.md in the KH2 documentation so that its title no longer says KH1 in it, since the KH1 documentation has been placed in its own folder and I don't believe it makes sense for the file types of multiple games to be tracked together.
> Initial KH1 Documentation

- docs/kh2/file/type/idx.md
This is part of a small suite of PRs I'm trying to do today;
In a nutshell this adds kaitai structure definition to the kh2 docs to make it easier to understand the file formats and to have more efficient parsers(http://kaitai.io/ explains how to generate parsers for different languages including C#). Some of those PRs will also include additional documentation for other file formats.
This specific PR only adds the kaitai definition of the IDX format.
> [KH2 DOC + KSY] IDX

- docs/kh2/file/type/bgm.md
This is part of a small suite of PRs I'm trying to do today;
In a nutshell this adds kaitai structure definition to the kh2 docs to make it easier to understand the file formats and to have more efficient parsers(http://kaitai.io/ explains how to generate parsers for different languages including C#). Some of those PRs will also include additional documentation for other file formats.
This specific PR adds a basis for the BGM format documentation along with a very basic Katai struct definition.
I'll need some input on this one: commands have a variable size, as such is there any preferred way to output that with your tables?
> [KH2 DOC + KSY] BGM

- OpenKh.Kh2/Imgd.Create.cs
This reverts a change that caused some tests failing due to Imgd.Create that was creating Imgd textures with red and blue channels swapped
> Revert "Imgd.Create now inverts correctly the blue and red channels"

- CONTRIBUTING.md
An user reported that the server's link is expired (https://github.com/Xeeynamo/OpenKh/issues/50).
This pull request will update the link with a new one once accepted and merged.
> Renewed Discord server invite link

- OpenKh.Tools.Common/Controls/KingdomTextArea.cs
0x80 is the maximum opacity on the PS2, so the renderer should display the colors accordingly.
> Calculate alpha values accordingly to PS2 GPU

- OpenKh.Tools.Kh2TextEditor/OpenKh.Tools.Kh2TextEditor.csproj
- OpenKh.Tools.Kh2TextEditor/Services/CsvTextExporter.cs
- OpenKh.Tools.Kh2TextEditor/Services/CsvTextImporter.cs
- OpenKh.Tools.Kh2TextEditor/Services/ExchangeableMessage.cs
- OpenKh.Tools.Kh2TextEditor/Services/ITextExporter.cs
- OpenKh.Tools.Kh2TextEditor/Services/ITextImporter.cs
- OpenKh.Tools.Kh2TextEditor/Services/PlainTextExporter.cs
- OpenKh.Tools.Kh2TextEditor/Services/TextExporters.cs
- OpenKh.Tools.Kh2TextEditor/Services/TextImporters.cs
- OpenKh.Tools.Kh2TextEditor/Services/XmlTextExporter.cs
- OpenKh.Tools.Kh2TextEditor/Services/XmlTextImporter.cs
- OpenKh.Tools.Kh2TextEditor/Services/YamlTextExporter.cs
- OpenKh.Tools.Kh2TextEditor/Services/YamlTextImporter.cs
- OpenKh.Tools.Kh2TextEditor/ViewModels/MainViewModel.cs
- OpenKh.Tools.Kh2TextEditor/Views/MainWindow.xaml
Implement text exporters #58:
- txt
- csv
- xml
- yml
Main menu:
Format filters:
> Implement text importers/exporters

- OpenKh.Tools.BarEditor/ViewModels/BarViewModel.cs
- OpenKh.Tools.BbsEventTableEditor/ViewModels/MainViewModel.cs
- OpenKh.Tools.DpdViewer/ViewModels/DpdViewModel.cs
- OpenKh.Tools.ImageViewer/ViewModels/ImageViewerViewModel.cs
- OpenKh.Tools.Kh2TextEditor/ViewModels/MainViewModel.cs
- OpenKh.Tools.LayoutViewer/ViewModels/MainViewModel.cs
- OpenKh.Tools.LevelUpEditor/ViewModels/LvupViewModel.cs
- OpenKh.Tools.ObjentryEditor/ViewModels/MainViewModel.cs
- azure-pipelines.yml
As the old implementation of the File Dialog had issues with saving the selected extension, this PR tackles to replace all old usages with the new one.
> Update FileDialog usages to use new implementation

- OpenKh.Kh2/Objentry.cs
- OpenKh.Tests/kh2/ObjentryTests.cs
- OpenKh.Tools.ObjentryEditor/Converters/EnumDescriptionConverter.cs
- OpenKh.Tools.ObjentryEditor/ViewModels/MainViewModel.cs
- OpenKh.Tools.ObjentryEditor/ViewModels/ObjentryViewModel.cs
- OpenKh.Tools.ObjentryEditor/Views/MainWindow.xaml
- OpenKh.Tools.ObjentryEditor/Views/ObjentryView.xaml
- docs/kh2/file/type/00objentry.md
Updated some previous unknown fields and the documentation
> Objentry additions

- OpenKh.Tools.Common/Controls/DrawPanel.cs
When I launched OpenKh.Tools.Kh2TextEditor, System.EntryPointNotFoundException raised.
In this is small patch, it uses P/Invoke [memcpy](http://pinvoke.net/default.aspx/msvcrt/memcpy.html) in msvcrt.dll.
> Redirect from CopyMemory to memcpy.

- OpenKh.Tools.LayoutViewer/Properties/Settings.Designer.cs
Fix start up problem of LayoutViewer on launching via Visual Studio 2019: `System.NullReferenceException: 'Object reference not set to an instance of an object.'`
Fix #109
> Set default value to BackgroundColor

- OpenKh.Command.MsgTool/Program.cs
- OpenKh.Kh2/Contextes/FontContext.cs
- OpenKh.Tools.Common/Kh2Utilities.cs
- OpenKh.Tools.Kh2SystemEditor/Extensions/BarExtensions.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/SystemEditorViewModel.cs
- OpenKh.Tools.Kh2TextEditor/ViewModels/MainViewModel.cs
- OpenKh.Tools.LevelUpEditor/ViewModels/LvupViewModel.cs
The Pull Request #107 renamed `EntryType.Binary` to `EntryType.List` and added a `EntryType.Binary` for a different kind of value. 
But most of the tools did not picked up the change and are still using the `EntryType.Binary`  rather than `EntryType.List`. This change breaks tools and game engine and the pull request aims to fix it.
> Fixes countless bugs that risked to damage files changed from #107

- OpenKh.Kh2/Messages/MsgSerializer.cs
- OpenKh.Tests/kh2/MsgSerializerTests.cs
```
OpenKh.Command.MsgTool.exe -i H:\KH2fm.yaz0r\msg\jp\bb.bar
```
This will create `"H:\KH2fm.yaz0r\msg\jp\al.xml"`
```xml
<?xml version="1.0" encoding="utf-8"?>
<messages>
<message id="11">
<text>１０１ÙÖ–?jü02</text>
<text>Ù??▲o0j、b—ß7uh</text>
</message>
<message id="12">
<text>１０２ÙÖ–?lc7èâá</text>
</message>
<message id="13">
<text>１０３426Ò2s16f1ÙÖ–?</text>
<text>Ù??▲o0j、426Ò2u3s</text>
</message>
<message id="14">
<text>１０４??´</text>
<unk value="FF" />
<text>?jpkc</text>
<text>Ù??▲o0j、??–?lyºá</text>
</message>
...
</messages>
```
Currently Japanese decoder isn't shipped so please someone check this please! (by using English version or etc...)
> Fixing A XML serialization problem on OpenKh.Command.MsgTool.

- OpenKh.Command.HdAssets/Program.cs
- OpenKh.Tests/OpenKh.Tests.csproj
- README.md
- azure-pipelines.yml
- build.ps1
- build.sh
- openkh_alias
- pre-build.ps1
There are also additional code and documentation polishing here and there for a better "consumer" experience.
> Add scripts to build from Windows and Linux

- OpenKh.Game/Content/KingdomShader.fx
- OpenKh.Game/Models/Mesh.cs
- OpenKh.Game/MonoDrawing.cs
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/Shaders/KingdomShader.cs
- OpenKh.Game/States/MapState.cs
- OpenKh.Kh2/ModelTexture.cs
This fixes some of the odd texture rendering glitches caused by the inability of emulating the "Texture Wrap Mode" as PlayStation 2 internally does.
BEFORE
AFTER
> Add custom shader to simulate PS2 behaviours

- OpenKh.Game/Debugging/DebugOverlay.cs
- OpenKh.Game/Global.cs
- OpenKh.Game/MonoDrawing.cs
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/States/TitleState.cs
This pull request adjusts the aspect ration based on which game build is loaded. PS2, PS3 and PS4 files will work, although for ReMIX the HD Asset content needs to be stripped.
This is how it looks using PS2 files:
This is how it looks using ReMIX files:
The text is not positioned on the far top-left when the wide-screen mode is used, but I am not concerned since it is only visible for debugging purposes.
Also I zoomed out the output by 2x in `Global.ResolutionBoostRatio`. Right now I would just keep it there. But in the future I propose to have some kind of configuration file to give flexibility to who does not have the source code to modify resolution boost and other stuff.
> Fix aspect ratio for ReMIX build

- azure-pipelines.yml
- build.ps1
Fixes the following two problems:
* The script `build.ps1` fails if you run it on Windows twice. Reason is because the file `OpenKh.Windows.sln` is created but never deleted or replaced.
* Previously we reached a point where OpenKH binaries were stored in a folder called `openkh` inside the zip you can download in GitHub Release. That was very useful on Linux, since the simple command `unzip openkh-xxx.zip` would just un-zip it to its directory. But with the recent releases, if you extract the content of the zip file, everything will be extracted in the directory you're in. And this is not ideal. Also it is useful on Windows too, where you can just right-click and do "extract here".
> Fix automated builds

- OpenKh.Common/Archives/HdAsset.cs
- OpenKh.Game/DataContent/HdAssetContent.cs
- OpenKh.Game/Infrastructure/Kernel.cs
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Tests/Archives/HdAssetTests.cs
This fixes the issue #124, where it was not possible to load PS4 remastered assets without stripping out the HD content.
#124 suggests to prompt the user to strip the HD stuff, which implies that the game files would be modified. This pull request takes a step further and just let the game engine to work without modifying them. The performance impact of this pull request is that now the game uses more ram for PS4 files, since all the HD textures will be loaded in memory as well.
When the HdAsset support for PS3 will be implemented, there will be potentially no changes to the game engine to make it working for PS3 too.
Finally, there are minor API changes:
* `HdAsset.New()` has been deleted, since it would make more sense to just invoke `new HdAsset()`
* Adds `HdAsset.IsValid`, which tries …
> HD Asset detection

- docs/kh2/file/raw-texture.md
This update describes animation metadata for raw textures in KH2 (BAR type `0x7`). This includes sprite animations for both map and MDLX textures, as well as UV scrolling for map textures.
I attempted to match markdown in this doc, but please let me know if I should make any changes.
> Add info on KH2 animated textures to raw-texture.md

- OpenKh.Tools.Kh2PlaceEditor/OpenKh.Tools.Kh2PlaceEditor.csproj
- OpenKh.Tools.Kh2PlaceEditor/ViewModels/PlaceViewModel.cs
Fixes the following error when using Kh2PlaceEditor
> Use Shift-JIS in .NET Core

- OpenKh.Engine/Parsers/NewModelParser.cs
Fixes a rendering glitch where the UV coordinates were not set in the right way.
PLEASE NOTE that in order to completely fix this glitch, [this patch](https://github.com/Xeeynamo/OpenKh/pull/133/files#diff-1b5378629a9e30fab7803dbbd7bfb72eR44) from #133 must be applied first, or instead of the "serration" you would just see black textures.
> Fix texture serration glitch

- OpenKh.Tools.Common/Controls/DrawPanel.cs
I noticed that `OpenKh.Tools.LayoutViewer` was great editor. Thus I wanted to play layout/sequence with less flicker.
This pull request is a small patch to improve it a bit.
> Less flicker on DrawPanel rendering.

- OpenKh.Tools.BarEditor/Services/ToolsLoaderService.cs
- Try to load plugin from `.dll` instead of `.exe`
- Xeeynamo/XeEngine.Tools.Public#2 is also needed to succeed initialization of `ImageViewerViewModel._imageFormatService` which throws `TypeInitializationException` (on resolving `OpenKh.Bbs`).
> Try to load plugin from `.dll` instead of `.exe`

- OpenKh.Game/DataContent/StandardDataContent.cs
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/Program.cs
Previously you had to put all the game files into the same directory where binaries were located. I changed it to fetch game data from the folder "data".
It is also possible to specify the game data directory through command line, so you can just invoke `dotnet OpenKh.Game.dll /mnt/disc0`.
> Change location for game content

- OpenKh.Game/OpenKh.Game.csproj
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/Program.cs
* Game could not find KH2.IDX when passing the data path as argument
* Exceptions were always caught, making debugging harder. It is now fixed.
* Printing version of the game in logs, so it would be easier to understand which version was causing a specific crash.
> Fix KH2.IDX path argument

- OpenKh.Game/Infrastructure/InputManager.cs
- OpenKh.Game/Infrastructure/RepeatableKeyboard.cs
- OpenKh.Game/OpenKhGame.cs
This pull request adds key pressing pulse in debugMenu.
It uses actual SPI_GETKEYBOARDDELAY/SPI_GETKEYBOARDSPEED values obtained from [SystemParametersInfoA function (winuser.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfoa) Win32 API.
You can change it from `control.exe keyboard`
> Implement key repeats on debugMenu.

- OpenKh.Command.IdxImg/Program.cs
- OpenKh.Kh2/Idx.cs
- OpenKh.Kh2/IdxName.cs
- docs/tool/index.md
Fix the following issues:
* Program crashed if the output directory was not specified.
* Program crashed when the tool was called from a different directory.
* Program was stuck in a potential endless loop when an invalid IDX file was passed.
* Tool was not shown to Tools page in OpenKH docs
> KH2 IdxImg improvements

- OpenKh.Tools.Common/Rendering/SpriteDrawingDirect3D.Context.cs
By accident, I was using features required from Windows 10 Creators Update. But those are actually not required for few users that wanted to use OpenKH tools for Windows 7. This PR lowers the OS requirement, allowing Windows 7 users to use all the OpenKH stack.
> Add Windows 7 compatibility

- OpenKh.Command.ImgTool/OpenKh.Command.ImgTool.csproj
- OpenKh.Command.ImgTool/Program.cs
- OpenKh.Command.ImgTool/Utils/ImgdBitmapUtil.cs
Fixed 2 problems in ImgdBitmapUtil of `OpenKh.Command.ImgTool`:
1. 4bpp bitmap size is doubled. https://github.com/Xeeynamo/OpenKh/issues/162#issuecomment-660421260
2. 4bpp bitmap pixel-order is invalid. https://github.com/Xeeynamo/OpenKh/issues/162#issuecomment-660431065
Also added 4 commands. `fix-imz` and `swap-imz-pixel`  for fixing 1 and 2. `scan-imd` and `scan-imz` for diagnostics purpose.
```
Commands:
fix-imz         imz file -> imz file (fix 4-bpp doubled bitmap size)
scan-imd        imd file -> display summary
scan-imz        imz file -> display summary
swap-imz-pixel  imz file -> imz file (swap 4-bpp hi/lo pixel)
```
scan-imz:
```bat
OpenKh.Command.ImgTool.exe scan-imz C:\Users\KU\Desktop\title_aq_test.imz
0:
PixelFormat: Indexed8
Width: 128
Height: 128
IsSwizzled: false …
```
> Fix 4-bpp imd/imz generator of `OpenKh.Command.ImgTool` and so on

- OpenKh.Engine/Extensions/ImageReadExtensions.cs
- OpenKh.Imaging/ImageDataHelpers.cs
- OpenKh.Kh2/RawBitmap.cs
There are pixel-swap problems when converting from 4-bpp bitmap data to native bitmap. Currently there are 3 parts doing this:
- `OpenKh.Engine/Extensions/ImageReadExtensions.cs` for `XNA` tools usage
- `OpenKh.Imaging/ImageDataHelpers.cs` for `WPF` tools usage
- ` GDI+` usage fixed by #164 
This pull requests fixes `XNA` and `WPF` parts.
`OpenKh.Tools.ImageViewer`
`OpenKh.Game`
Fix #165
> Fix pixel-swap on loading 4-bpp imd/imz images

- OpenKh.Kh2/Ps2.Reform4.cs
- OpenKh.Kh2/RawBitmap.cs
This pull request fix a regression from #164 to fix #165 .
#164 fixes the useless logic of swapping twice some bitmaps, but unfortunately it was swapping 4bpp endianness for some IMGD that were not supposed to be swapped too. I figured out that it was enough to change the 4bpp un/swizzling logic.
This is 100% accurate to what PlayStation 2 internally does. Image creation is fixed as well.
> Internally swap swizzled 4bpp IMGD files

- OpenKh.Tools.LayoutEditor/App.cs
Change the "link to PCSX2" function to Ctrl+L instead of Ctrl+A. 
(Ctrl+A is more convenient freed up since it's an easy "highlight all" function built into software and OSes.)
> Hotkey change (Layout Editor)

- OpenKh.Tools.LayoutEditor/AppLayoutEditor.cs
- OpenKh.Tools.LayoutEditor/AppSequenceEditor.cs
- OpenKh.Tools.LayoutEditor/Controls/ImSequencer.cs
> Fix various major issues with Layout Editor

- OpenKh.Engine/Parsers/MdlxParser.cs
- OpenKh.Game/States/MapState.cs
As the screenshot shows. The only problem is that now character models are flipped. But that is because OpenKH did not fully reversed those yet.
> Fix flipped map glitch

- OpenKh.Game/Config.cs
- OpenKh.Game/DataContent/ModDataContent.cs
- OpenKh.Game/OpenKhGame.cs
This is a quick one. I often found that when I wanted to test modded asset on OpenKH game engine, I had to modify the original game files and often accidentally losing the source.
This adds mod support. By default it tries to find files in the `mod` folder. If the file is found, it loads the modded one. If it is not, it is going to fall back to the original file.
Of course you can set any path from the `config.yml`. I personally set the VFS of CC's DynamicLoader.
> Add simple file mod support

- docs/kh2/file/type/msn.md
Some tables weren't rendered properly on openkh.dev
Additionally, i've changed the definition of pos 0xD, as it's holds the bonus reward.
> Fix formatting on msn.md

- OpenKh.Tools.Common/Rendering/SpriteDrawingDirect3D.Drawing.cs
Very clear from the title. It was preventing to use the editor in certain scenario.
> Fix crash for TextEditor when '{:clear }' was supposed to be draw

- OpenKh.Command.ImgTool/Program.cs
- OpenKh.Command.ImgTool/Utils/ImgdBitmapUtil.cs
Adding command line option `-s|--swizzle` to activate swizzle on ImgTool.
```bat
H>OpenKh.Command.ImgTool.exe imd -h
png file -> imd file
Usage: OpenKh.Command.ImgTool imd [options] <PngFile>
Arguments:
PngFile                    Input png
Options:
-?|-h|--help               Show help information
-o|--output <OUTPUT_IMD>   Output imd. Default is current dir, and file extension to imd.
-b|--bpp <BITS_PER_PIXEL>  Set bits per pixel: 4, 8, or 32
-p|--pngquant              Use `pngquant.exe` -- lossy PNG compressor. Download `pngquant.exe` and place it beside
this program, current directory, or PATH.
-n|--nquant                Use embedded nQuant.Core color quantizer. This is default selection.
-s|--swizzle               Enable swizzle.
H>OpenKh.Command.ImgTool.exe imz -h
png, imd or imz …
```
> OpenKh.Command.ImgTool swizzle-on support for imd/imz

- OpenKh.Command.ImgTool/Utils/QuantizerFactory.cs
Sometimes ImgTool hanged up on conversion from png to imgd, when enabling pngquant.
This pull request fixes potential problem by closing stdin of pngquant process.
> Small fix to ImgTool: prevent pngquant from blocking

- OpenKh.Command.ImgTool/Utils/ImgdBitmapUtil.cs
- OpenKh.Command.ImgTool/Utils/QuantizerFactory.cs
Two fixes:
(1) Loose of transparent color.
Original (export from KH1)
Converted with ImgTool (nQuant). Loosing transparent color.
Converted with ImgTool (nQuant). Holding transparent color.
(2) flatting image color palette
Original imd → png
Converted with ImgTool (nQuant). Loosing detail of color intensity.
Converted with ImgTool (nQuant). Keep color intensity.
PS. Another sample using quantization
png:
Converted with ImgTool (nQuant). Alpha channel looks good.
Technically:
(1) Do not apply quantization if not required. (e.g. 8-bpp image with simultaneously palette color count usage less or equal than 256)
(2) Tweak nQuant parameter: `alphaThreshold: -1` and `alphaFader: 1,`
> ImgTool alpha issue fix

- OpenKh.Command.CoctChanger/Program.cs
- OpenKh.Command.DoctChanger/Program.cs
- OpenKh.Command.MapGen/Models/BigMesh.cs
- OpenKh.Command.MapGen/Models/MapGenConfig.cs
- OpenKh.Command.MapGen/Models/MaterialDef.cs
- OpenKh.Command.MapGen/Program.cs
- OpenKh.Command.MapGen/Utils/CollisionBuilder.cs
- OpenKh.Command.MapGen/Utils/MapBuilder.cs
- OpenKh.Kh2/Doct.cs
- docs/tool/CLI.CoctChanger/index.md
- docs/tool/CLI.DoctChanger/index.md
- docs/tool/CLI.MapGen/index.md
Copy COCT data to DOCT:
- Use COCT data to create DOCT data.
- Usually KH2 asset maps use different data for COCT/DOCT.
Roughen COCT resolution:
- COCT and DOCT data basically needs "recursive call".
- Currently COCT data has deep depth. About COCT processing it has no problem. About DOCT processing it has rendering problem. So try to roughen COCT for example, and lower splitter resolution.
Visualize COCT data quantity in numerical form.
```txt
H>OpenKh.Command.CoctChanger.exe show-stats H:\KH2fm.OpenKH\map\jp\tt05.map
352 collision mesh groups.
306 collision meshes.
1,076 collisions.
1,968 vertices.
869 planes.
943 bounding boxes.
11 surface flags.
205 collision mesh groups.
151 collision meshes.
250 collisions.
492 vertices.
236 planes.
151 bounding boxes.
3 surface flags.
55 collision …
```
> MapGen: Copy COCT data to DOCT, and roughen COCT resolution

- OpenKh.Engine/Renders/SequenceRenderer.cs
- OpenKh.Tests/Engine/SequenceRendererTest.cs
- OpenKh.Tools.LayoutEditor/AppSequenceEditor.cs
I found we were using the wrong interpolation. It is not cubic, but it is an ease in-out interpolation, which have a slow start and end but a fast middle.
Before the fix:
After the fix:
---
Notice here how the fixed version fades out the "light" on the title screen quicker and the animations of NEW GAME and LOAD are way more accurate now:
Before the fix:
After the fix:
---
I noticed that the interpolation was wrong while I was developing the menu. I clearly remembered that the animation when you open the menu slows down when close to the end of the animation. This was definitively not happening before the fix, as the menu would instantly appear.
Before the fix:
After the fix:
> Fix sequence interpolation

- OpenKh.Engine.MonoGame/KingdomShader.cs
- OpenKh.Engine/Parsers/Kddf2/ImmutableMesh.cs
- OpenKh.Engine/Parsers/Kddf2/Kkdf2MdlxBuiltModel.cs
- OpenKh.Engine/Parsers/Kddf2/Kkdf2MdlxParser.cs
- OpenKh.Engine/Parsers/Kddf2/TriangleRef.cs
- OpenKh.Engine/Parsers/MdlxParser.cs
- OpenKh.Game/Content/KingdomShader.fx
- OpenKh.Game/States/MapState.cs
- OpenKh.Kh2/ModelTexture.cs
- OpenKh.Ps2/VpuPacket.cs
Summary of changes with before/after comparison:
* Fix double/missing map geometry and some stray triangles.
* Support alpha masking for opaque meshes, and disable depth write in the blend passs for map meshes. This should resolve bad transparency and z-fighting in some areas.
* Fix corrupted textures by skipping data deswizzling if the upload pixel format is not PSMCT32.
* Support alpha blending for entities for specific mesh segments where blending should be applied.
> Rendering bug fixes for OpenKh.Game

- .editorconfig
- .gitattributes
- OpenKh.sln
I need to gain again some momentum in this project. This is a very small PR that suggests contributors to strict code formatting rules. I also became aware that shell scripts on Linux do not work with `crlf` line ending. Since there are minor inconsistencies between the text encoding and line ending, the rules will force the editor to always use UTF-8 without BOM and `lf` in all occasions with few exceptions.
> Specify line ending and formatting rules

- OpenKh.Tools.Kh2MapStudio/App.cs
- OpenKh.Tools.Kh2MapStudio/OpenKh.Tools.Kh2MapStudio.csproj
- OpenKh.Tools.Kh2MapStudio/Program.cs
You can specify `<KH2 GamePath>` at command line.
```bat
H:\Proj\OpenKh>H:\Proj\OpenKh\OpenKh.Tools.Kh2MapStudio\bin\Debug\netcoreapp3.1\OpenKh.Tools.Kh2MapStudio.exe --help > help.txt
H:\Proj\OpenKh>type help.txt
1.0.0
Usage: OpenKh.Tools.Kh2MapStudio [options] <KH2 GamePath>
Arguments:
KH2 GamePath
Options:
--version     Show version information
-?|-h|--help  Show help information
```
Usage
```bat
H:\Proj\OpenKh>H:\Proj\OpenKh\OpenKh.Tools.Kh2MapStudio\bin\Debug\netcoreapp3.1\OpenKh.Tools.Kh2MapStudio.exe H:\KH2fm.OpenKH
```
After launch:
Fix #269
> Add command line support to OpenKh.Tools.Kh2MapStudio

- OpenKh.Tools.ImageViewer/ViewModels/ImageViewerViewModel.cs
Fix OpenKh.Tools.ImageViewer doesn't clear bar data before saving image, when it is launched by OpenKh.Tools.BarEditor as embedded tool.
> ImageViewer: clear current bar entry data before saving

- OpenKh.Engine.MonoGame/Extensions.cs
- OpenKh.Engine.MonoGame/KingdomTexture.cs
- OpenKh.Engine.MonoGame/MeshGroup.cs
- OpenKh.Engine/OpenKh.Engine.csproj
- OpenKh.Game/Entities/ObjectEntity.cs
Allow to load FBX models with their PNG textures into OpenKH game engine. Thanks to this it is now possible to show models from Kingdom Hearts Melody of Memory and not only as FBX is a very wide and supported format.
This PR will not change the behaviour of the current game engine. If you want to achieve the result shown in the screenshot above, paste this portion of code in `LoadMesh` function from `ObjectEntry.cs`. Of course replace the path with the one from your computer.
```csharp
if (objEntry.ModelName == "PLAYER")
{
Mesh = FromFbx(graphics, @"D:\KHMOM\CHARACTER0000033\CHARACTER0000033_md.fbx");
return;
}
```
> Add FBX model loader

- OpenKh.Tools.Kh2MapStudio/App.cs
- OpenKh.Tools.Kh2MapStudio/Settings.Designer.cs
- OpenKh.Tools.Kh2MapStudio/Settings.settings
Following #269 and #277 , I am removing a hardcoded path that has been pushed by mistake. Also when you open the application, the tool will try to open the last open game folder.
> MapStudio remembers last game folder open

- OpenKh.Common/DictionaryExtensions.cs
- OpenKh.Game/Infrastructure/StateInitDesc.cs
- OpenKh.Game/OpenKh.Game.csproj
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/Program.cs
- OpenKh.Game/States/MapState.cs
A feature I use A LOT while I work with our game engine is that I want to boot straight to a specific map with specific settings. Every time I end up modifying manually the code and try to remember to not commit it. This is not an ideal scenario.
The pull request allows to do so by specifying the required boot settings from a command line. Since you usually set arguments in the "debug" tab of Visual Studio (or whatever is your favourite IDE), this will allow very fast testing. For example, when I want to spawn into "The Dark Margin" map I can just use the arguments `.\KH2\export_fm -v -state 1 -world es -place 0 -spawn-map 25`. 
You can also invoke `dotnet OpenKh.Game.dll --help` to know more about the possible settings:
> Boot parameters for OpenKH game engine

- OpenKh.Bbs/OpenKh.Bbs.csproj
- OpenKh.Common/OpenKh.Common.csproj
- OpenKh.Engine/OpenKh.Engine.csproj
- OpenKh.Imaging/OpenKh.Imaging.csproj
- OpenKh.Kh2/OpenKh.Kh2.csproj
- OpenKh.Ps2/OpenKh.Ps2.csproj
The low level libraries were using .NET Standard 2.0 and the only reason for that was to have backward compatibility with .NET Framework 4.7.2. Now that we have all the tools in .NET Core 3.1 and .NET 5 recently became a thing, there is no need anymore to shy away from .NET Core 3.1 features for the low level libraries.
> Upgrade to .NET Core 3.1 for every library

- OpenKh.Engine/Extensions/ImageReadExtensions.cs
- OpenKh.Engine/Renders/IMessageRenderer.cs
- OpenKh.Imaging/ImageDataHelpers.cs
- OpenKh.Kh2/RawBitmap.cs
- OpenKh.Tools.Common/Controls/KingdomTextArea.cs
- OpenKh.Tools.ImageViewer/Services/ImageFormatService.cs
- OpenKh.Tools.ImageViewer/Services/ImageFormatSevice.Kh2Font.cs
Issues fixed:
* Font swizzled in KH2TextEditor (regression from #223, issue mentioned here https://discord.com/channels/409140906625728532/777560811114725407/782359965943857162)
* Text too small in KH2TextEditor (regression from #241, issue mentioned here #287)
Bonus:
* ImageViewer can now open and display correctly a `fontimage.bar` file. The `icon` entry still have messed-up colours. There is currently no save functionality for `fontimage.bar`.
> Fix various issues linked to fontimage usage

- OpenKh.Game/Program.cs
An user mentioned a [unexpected behaviour](https://discord.com/channels/409140906625728532/567061704849096725/779595641135300608) in the latest builds of OpenKh.Game. I realised that the mistake was that the game was always asking for the game's path as a command line argument. This fixes the issue.
NOTE: From now on you will need to change your debugging configuration by specifying `--path YOUR_GAME_PATH` if you do not want to use the settings from `config.yml`.
> Fix bug where OpenKh.Game always need at least an argument

- OpenKh.Kh2/Mdlx.cs
- OpenKh.Kh2/Motion.cs
- OpenKh.Research.Kh2Anim/Program.cs
- OpenKh.Research.Kh2Anim/Subcommands/BakeCommand.cs
- OpenKh.Research.Kh2Anim/Subcommands/FryCommand.cs
- OpenKh.Research.Kh2Anim/Subcommands/SimpleMdlxCommand.cs
- OpenKh.Research.Kh2Anim/TypeConverters/TimelineTableConverter.cs
- OpenKh.Research.Kh2Anim/Utils/AnbBarWrapper.cs
- OpenKh.Research.Kh2Anim/Utils/MdlxMaker.cs
- OpenKh.sln
**Note:** this pr contains merged codes from https://github.com/Xeeynamo/OpenKh/pull/310
Usage:
```
$ ./OpenKh.Research.Kh2Anim.exe fry -h
Fry fake motion
Usage: OpenKh.Research.Kh2Anim fry [options]
Options:
-?|-h|--help                                Show help information
-o|--output-mset <OUTPUT_MSET>              Output file: model.mset
-l|--frame-loop <FRAME_LOOP>                Unknown
-e|--frame-end <FRAME_END>                  Unknown
-c|--frame-count <FRAME_COUNT>              Unknown
-a|--total-frame-count <TOTAL_FRAME_COUNT>  Unknown
-f|--frame-per-second <FRAME_PER_SECOND>    FPS
-t|--timeline <TIMELINE>                    Interpolation,FrameTime,Value,TangentEaseIn,TangentEaseOut
(Nearest|Linear|Hermite|Zero),0.00,0.00,0.00,0.00
-p|--prefix <PREFIX> …
```
> Implement: fry fake motion command to OpenKh.Research.Kh2Anim

- docs/kh3/pawns.md
e_ex043 is actually Dark Inferno, not Darkside and Lump of Horror is e_ex701.
> Add these two pawns

- OpenKh.Kh2/RawBitmap.cs
This PR fixes an oversight with RawBitmap swizzling where it applied a fix for 4bpp images to 8bpp images also.
This PR has been tested with everything except for OpenKH.Game and is functional.
Demo Images:
And here are IMGDs that I have tested (Swizzled and non-swizzled):
> Fix fontimage swizzling.

- OpenKh.Game/Infrastructure/Kernel.cs
- OpenKh.Kh2/Contextes/FontContext.cs
- OpenKh.Kh2/SystemData/Ftst.cs
- OpenKh.Kh2/SystemData/Item.cs
- OpenKh.Kh2/SystemData/Trsr.cs
- OpenKh.Tests/kh2/System03Tests.cs
- OpenKh.Tools.Kh2SystemEditor/Models/Export/ItemExport.cs
- OpenKh.Tools.Kh2SystemEditor/Models/Export/TrsrExport.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/FtstViewModel.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/ItemViewModel.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/SystemEditorViewModel.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/TrsrViewModel.cs
We currently have a namespace called `OpenKh.Kh2.System`, where all the structures from `00system.bin` and `03system.bin` are. The biggest problem is that if you import the namespace `using OpenKh.Kh2;`, you can not use anything anymore from the namespace `System`, which contains the fundamentals of .NET.
This PR renames it into `OpenKh.Kh2.SystemData`, fixing the issue. As we are now using `LF` instead of `CRLF`, I converted the files that have been changed to `LF` to keep consistency.
> Rename namespace + fix CRLF to LF

- OpenKh.Kh2/Motion.cs
- OpenKh.Tests/Imaging/Tm2Tests.cs
- OpenKh.Tests/kh2/MotionTests.cs
Workaround for broken mset motion data that is pointing to overflowed index of keyFrames and transformationValues.
To enable xunit batch test, set `KH2Dir` to valid path to asset files extracted by extractor:
```cs
private static string KH2Dir = @"H:\KH2fm.OpenKh\";
```
and uncomment:
```cs
//[Theory, MemberData(nameof(Source))]
```
And then build and run tests.
> Workaround for broken mset motion data

- OpenKh.Engine/Renders/Kh2MessageRenderer.cs
- OpenKh.Game/Debugging/DebugOverlay.cs
- OpenKh.Kh2/Messages/Internals/InternationalSystemDecode.cs
- OpenKh.Kh2/Messages/Internals/InternationalSystemEncode.cs
- OpenKh.Kh2/Messages/Internals/JapaneseEventDecode.cs
- OpenKh.Kh2/Messages/Internals/JapaneseSystemDecode.cs
- OpenKh.Kh2/Messages/Internals/TurkishSystemDecode.cs
- OpenKh.Kh2/Messages/MessageCommand.cs
- OpenKh.Kh2/Messages/MsgSerializer.Text.cs
- OpenKh.Kh2/Messages/MsgSerializer.cs
- OpenKh.Tests/kh2/MsgEncoderTests.cs
- OpenKh.Tests/kh2/MsgSerializerTests.cs
- OpenKh.Tools.Kh2TextEditor/ViewModels/MainViewModel.cs
- OpenKh.Tools.Kh2TextEditor/ViewModels/TextEditorViewModel.cs
- OpenKh.Tools.Kh2TextEditor/Views/TextEditorView.xaml
- docs/tool/GUI.Kh2TextEditor/index.md
Brings the following changes:
* Say goodbye to `{:newstring}` as you now just need to press Enter to insert a new line.
* If opening a `sys.bar`, autodetects if European or Japanese encoding needs to be used.
* When opening a message file, autodetects `fontimage.bar` and `fontinfo.bar` rather than loading then manually.
* Updates documentation according to the latest changes.
> KH2 Text Editor improvements

- OpenKh.Tools.Kh2MapStudio/ObjEntryController.cs
A quick fix to #342. It's a fast fix, but it's an effective one.
Screenshot:
> Fix MapStudio crashing when it loads a model with no textures.

- OpenKh.Engine.MonoGame/Camera.cs
- OpenKh.Engine.MonoGame/Extensions.cs
- OpenKh.Engine.MonoGame/KingdomShader.cs
- OpenKh.Engine.MonoGame/KingdomTexture.cs
- OpenKh.Engine.MonoGame/MonoSpriteDrawing.cs
- OpenKh.Engine.MonoGame/OpenKh.Engine.MonoGame.csproj
- OpenKh.Engine/Parsers/MdlxParser.cs
- OpenKh.Game/Infrastructure/Kh2Field.cs
- OpenKh.Game/States/MapState.cs
- OpenKh.Tools.Common.CustomImGui/ImGuiEx.cs
- OpenKh.Tools.Kh2MapStudio/App.cs
- OpenKh.Tools.Kh2MapStudio/MapRenderer.cs
- OpenKh.Tools.Kh2MapStudio/Windows/CameraWindow.cs
To manage matrices and vectors, we currently have both `System.Numerics` and `Microsoft.Xna.Framework`. `System.Numerics` is faster and with the latest versions of .NET Core, the compiler can generate specialised instructions for certain processors to boost performance even more. But `Microsoft.Xna.Framework`, which is part of MonoGame, have basically the same functionality but slower.
This PR aims to remove some overhead caused by the MonoGame library, to standardise the math library following the .NET Core specifications and to remove the dependency of it here and there.
> Remove monogame dependency and slightly improve performance

- OpenKh.Command.PmoConverter/Program.cs
- OpenKh.Command.PmpConverter/Program.cs
- OpenKh.Engine.MonoGame/MeshLoader.cs
- OpenKh.Engine/Parsers/Kkdf2MdlxParser.cs
- OpenKh.Engine/Parsers/MdlxParser.cs
- OpenKh.Engine/Parsers/PmoParser.cs
- OpenKh.Game/Entities/ObjectEntity.cs
- OpenKh.Tools.Kh2MapStudio/MapRenderer.cs
[As already mentioned](https://discord.com/channels/409140906625728532/735110384398106694/804270502821888001), it fixes an issue [mentioned in discord](https://discord.com/channels/409140906625728532/567065170879184910/799395407163031552) to simulate a [known behaviour](https://discord.com/channels/409140906625728532/565971398539870273/784232466985779240) in Kingdom Hearts games.
> Vertices uses float colors to simulate bloom effect

- OpenKh.Common/Log.cs
- OpenKh.Game/Config.cs
- OpenKh.Game/DataContent/IdxDataContent.cs
- OpenKh.Game/DataContent/ModDataContent.cs
- OpenKh.Game/DataContent/StandardDataContent.cs
- OpenKh.Game/Debugging/Log.cs
- OpenKh.Game/Entities/ObjectEntity.cs
- OpenKh.Game/Infrastructure/Kernel.cs
- OpenKh.Game/Infrastructure/Kh2Field.cs
- OpenKh.Game/Menu/MenuStatus.cs
- OpenKh.Game/OpenKhGame.cs
- OpenKh.Game/Program.cs
- OpenKh.Game/States/MapState.cs
- OpenKh.Game/States/MenuState.cs
- OpenKh.Game/States/Title/TitleState.cs
Move `Log` from `OpenKh.Game` to `OpenKh.Common`, so every project can use it by just doing `Log.Error("MyError")` without any set-up. The log takes the name of the executable file, so if you log from the app `OpenKh.Tools.MapStudio` the log will be called `OpenKh.Tools.MapStudio.log`. You do not need to deal with any configuration, _just log™_
Another feature is that you can hook incoming log messages. Just do a `Log.OnLogDispatch += MyLogHandler` to get them. That way you can for example display log messages into an application.
> Standardise OpenKH Log across the entire codebase

- OpenKh.WinShell.IMDUtilities/OpenKh.WinShell.IMDUtilities.csproj
- OpenKh.WinShell.IMZUtilities/OpenKh.WinShell.IMZUtilities.csproj
- docs/tool/GUI.ImageViewer/index.md
- docs/tool/winshell/index.md
Basically redirects the `OpenKh.Winshell.Output` into `./bin` folder so it does not obstruct the `build.ps1` script. I modified the documentation of WinShell acoordingly other than indexing it on the docs.
> Fix build script when running twice

- OpenKh.Tools.ModsManager/ViewModels/ModViewModel.cs
Using streams is sometimes a good idea. 
This fixes the crash that is present if a mod image is loaded from a path with a space in it.
> Fix crash on image load. (Mod Manager)

- OpenKh.Kh2/SystemData/Item.cs
- OpenKh.Patcher/FmlvDTO.cs
- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tests/Patcher/PatcherTests.cs
- OpenKh.Tests/kh2/System03Tests.cs
- OpenKh.Tools.Kh2SystemEditor/ViewModels/ItemViewModel.cs
Cleaned up version of PR #452 . Adds functionality to the Patcher Processor that enables editing the following files using YAML:
* 00battle.bin
* Fmlv
* Lvup
* Bons
* 03system.bin
* Trsr
* Item
* 00objentry.bin
> Add ListReplace patching method and tests

- .github/workflows/auto-merge.yml
Apparently the Auto Merge for Dependabot broke due to a recent security change from GitHub. As described [in this post](https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60#issuecomment-806170152) there is a fix. This PR implements that fix as an attempt to fix it.
> Attempt to fix auto-merge

- OpenKh.Command.IdxImg/KingdomHearts1.cs
- OpenKh.Command.IdxImg/KingdomHearts2.cs
The PR #459 introduced some regressions where it was no longer possible to use the tool at all but to extract KH1 game's data. This restores all the intended functionalities.
> Fix broken OpenKh.Command.IdxImg

- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tests/Patcher/PatcherTests.cs
Allows editing of the `plrp` list in `00battle.bin`. This enables easy modification of starting stats and inventories of Sora, Donald, Goofy, and any guest characters in Kingdom Hearts 2. This includes Critical Bonuses for Sora.
[PlrpList.txt](https://github.com/Xeeynamo/OpenKh/files/6236492/PlrpList.txt) is an example source list that includes Sora's starting inventory and stats for Critical and Non-Critical difficulties.
> Add `plrp` modification to `listpatch` method.

- OpenKh.Patcher/PatcherProcessor.cs
Adds the `internal` type parameter to the `copy` method. This allows mods to rearrange game assets without bundling them.
Template:
```
- method: copy
name: $OUTPUT_FILE
source:
- name: $GAME_ASSET
type: internal
```
Example:
```
- method: copy
name: bgm/music097.win32.scd
source:
- name: bgm/music111.win32.scd
type: internal
```
The above `mod.yml` entry copies the content of `bgm/music111.win32.scd` to `bgm/music097.win32.scd` in the mod output directory.
> [Mod Manager] Create `internal` copy method type

- OpenKh.Kh2/Ard/AreaDataScript.cs
- OpenKh.Tests/kh2/ArdTests.cs
- docs/kh2/file/type/areadata.md
Makes 3 small adjustments
1 - Changes capacity from a float to an int, after careful testing in game and review of the disassembly
2 - Adds AllocPacket, which is unused in the actual game but is supported and can seemingly give memory related benefits to the PC version for modding
3 - Makes the If command actually throw a proper exception instead of failing on a bad parseInt
> fixes to ard script parse

- NOTICE
- docs/_config.yml
- docs/bbs/index.md
- docs/com/index.md
- docs/common/hdassets.md
- docs/common/tm2.md
- docs/ddd/index.md
- docs/engine/index.md
- docs/index.md
- docs/kh1/dictionary/mdls.md
- docs/kh1/index.md
- docs/kh2/dictionary/obj.md
- docs/kh2/index.md
- docs/kh3/index.md
- docs/khds/common/index.md
- docs/khds/days/index.md
- docs/khds/recoded/index.md
- docs/mom/index.md
- docs/other/coded/index.md
- docs/other/vcast/index.md
- docs/other/vr/index.md
- docs/recom/index.md
- docs/remasters/15plus25/index.md
- docs/remasters/28fcp/index.md
- docs/tool/index.md
In addition to adding the KH1 MDLS dictionary (courtesy of Rapid), I have finally added a sane way to go to the previous page on every single sub-index. I.e., going to the KH2 main index page will include a "Back to Index" link at the top. Sub-pages should include the same thing via clicking the game title at the top of each page as well, though I suppose it may be possible I missed some. Nevertheless, hopefully this improves navigation a fair bit.
Edit: Forgot to mention, I updated the `NOTICE` file, as well as the `docs/_config.yml` file too.
> Add KH1 MDLS dictionary + made index pages slightly better to "traverse"

- OpenKh.Egs/EgsTools.cs
Thanks to Topaz reporting some bugs, I fixed how many textures in a PAX should actually count for HD linking as well as correcting the offsets for some textures where duplicates exist.
There still seems to be the issue of how you should order your remastered textures if adding a new PAX to the game as there seems to be no way to tell by reading the new file how the textures should exactly be ordered. 
So while ass the offsets in the new file would be correct, the order of the textures in the remastered folder won't always be and thus require manually fixing every now and then.
> Fixed some PAX remastered texture linking issues

- OpenKh.Egs/EgsTools.cs
Some refactoring that removes a lot of redundancy in the code was done for the file classes.
In addition, offsets for RAW textures that use Pixel Storage Modes other than 8bpp should now be correct.
I'm not aware of any MDLX that uses a PSM other than 8bpp, but this was needed for *.map HD linking at least once I finally figure that out.
Sorry if I've been putting out quite a few PRs about this stuff btw.
> Some code cleanup and fixes for HD linking.

- OpenKh.Egs/EgsTools.cs
Fixes a bug found where remastered files without extensions would incorrectly get a full stop added to their name when patched in. Mainly this affected sound effects and voices found in the a.us files.
> Fixed hd asset patching for files without extensions

- OpenKh.Imaging/PngImage.cs
- OpenKh.Patcher/PatcherProcessor.cs
The new .NET 6 #598 has a breaking change on how [GZip decompression is handled](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams). We are using the library `DeflateStream` which is mainly used by `PngImage`. This bug affects the following products:
* PmoConverter
* PmpConverter
* Mods Manager
* Image Viewer
Essentially it is now impossible to just read byte by byte from `DeflateStream` so now we need a buffer to unload the decompressed data before reading it from a stream. Luckily `BufferedStream` does the trick and the fix is quite straightforward. I also took the opportunity to improve the error logging if a PNG acts weird.
> Fix PNG decompression

- .editorconfig
Fixes this damn message:
The current `.editorconfig` forces to use a certain end of line format. But on Windows and Linux, git transforms the end of line format based to the target operating system and Visual Studio follows that logic. The existing `.editorconfig` clashes with it making that issue.
This PR fixes the problem once for all for any operating system and for any IDE and text editor.
> Do not use end_of_line from .editorconfig

- OpenKh.Tools.ModsManager/Services/Pcsx2Injector.cs
I found that the MIPS instructions I wrote long time ago were either incomplete or incorrect. This code patch expands the capability of writing and injecting custom MIPS code to any MIPS Little Endian's code (eg. PlayStation 2 and PlayStation Portable).
> Enhance Mods Manager injection capabilities for PSP/PS2 games

- OpenKh.Engine/Motion/Kh2MotionEngine.cs
- OpenKh.Game/Config.cs
When closing the engine there was an occasional crash. This is now fixed. I also re-enabled the entity animation as it was commented out for some obscure reason.
> Fix OpenKH.Engine crash

- OpenKh.Tools.Kh2MsetEditor/OpenKh.Tools.Kh2MsetEditor.csproj
Removes the COM (Not Chain Of Memories) reference in KH2.msetEditor to fix the dotnet build command
> Remove COM reference in msetEditor to fix dotnet build

- OpenKh.Research.Panacea/KingdomApi.h
- OpenKh.Research.Panacea/OpenKH.cpp
- OpenKh.Research.Panacea/OpenKh.Research.Panacea.vcxproj
- OpenKh.Research.Panacea/Panacea.cpp
- OpenKh.Research.Panacea/dllmain.cpp
It now uses signatures to locate the functions it needs to hook, and my initial test shows that the signatures get a hit in every game in the 1.5+2.5 collection, including the launcher and theater. Currently I've left it locked to only supporting KH2, until such a time as the mod manager can support multiple games.
> Make Panacea Game/Version Agnostic

- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
These changes restore the previous folder structure of the "build only" option of Mods Manager, while also generating a "package map" file on the fly to keep track of which package the files belong to. If the patch or fast patch option is selected, that generated package map file is used to then rearrange the folder structure to match the one expected by the patcher code.
Special cases are added for `mod/scripts` and `mod/dlls` to keep compatibility with mods that are using that.
> Use a package map file to allow restructuring of files when patching

- OpenKh.sln
Currently `OpenKh.sln` is marked to open with `Visual Studio 2019`.
But I cannot build many tools, because Visual Studio 2019 doesn't recognize .NET 6.0.
```txt
Build started...
1>------ Build started: Project: OpenKh.Tools.Kh2SystemEditor, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\6.0.108\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(134,5): warning NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported.
```
So switching it to 'Visual Studio 2022' now so that Microsoft Visual Studio Version Selector will open `OpenKh.sln` with designated IDE.
> Open solution file with 'Visual Studio 2022'

- OpenKh.Kh2/Ard/AreaDataScript.cs
- OpenKh.Tests/kh2/ArdTests.cs
Hotfix for OpenKh.Tools.Kh2MapStudio.exe to allow spaces instead of tabs for sub commands, as tabs can't be entered.
> Hotfix for OpenKh.Tools.Kh2MapStudio.exe

- OpenKh.AssimpUtils/Kh2MdlxAssimp.cs
- OpenKh.Engine/Parsers/Kkdf2MdlxParser.cs
- OpenKh.Engine/Parsers/MdlxParser.cs
Fix Kh2MapStudio crashing by exception thrown. It occurred on opening map file . Recover PositionColoredTextured size to expected size.
```
System.ArgumentOutOfRangeException: Vertex stride of vertexDeclaration should be at least as big as the stride of the actual vertices. (Parameter 'vertexDeclaration')
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int32[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
at OpenKh.Tools.Kh2MapStudio.MapRenderer.RenderMeshNew(EffectPass pass, MeshGroup mesh, Boolean passRenderOpaque) in V:\OpenKh-mapgen\OpenKh.Tools.Kh2MapStudio\MapRenderer.cs:line 376
at …
```
> Fix Kh2MapStudio and Kh2MdlxEditor

- OpenKh.Kh2/Ard/AreaDataScript.cs
At Discord, an user reported that mod (GoA ROM) doesn't work.
This pr will fix this issue.
Reproduce:
1. Launch Mods Manager.
2. Mods menu → Install a new mod
3. e.g. `KH2FM-Mods-Num/GoA-ROM-Edition`
4. Turn on check
5. Game menu → Build... → Build only
The build operation will succeed without error after fix.
> Fix AreaSettings parser

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
Also hide a menu if it cannot be used. If a setting is updated by running the wizard a restart of the Mod Manager is required to properly hide or display a menu if the changed setting means one of the two menus visibility should change.
I had added some code to the end of the wizard relay command so whenever the wizard was run the variables were properly updated but without refreshing/redrawing? the Mod Manager window the visibility of the Mod Loader or PC Menu wouldnt change without restarting Mod Manager entirely
```
if (ConfigurationService.GameEdition == 2)
{
PC = true;
}
else
{
PC = false;
}
```
> Seperate the Mod Loader and Patching Menus

- .gitmodules
OpenKh depends on projects from `Xeeynamo/XeEngine.Tools.Public` repository.
But OpenKh contributors cannot provide fix problems or improve functionality easily (simply it is not under control of OpenKh project).
Thus I have forked `XeEngine.Tools.Public` repository to OpenKh organization, so that we can manage it demands to our needs.
It is MIT licensed.
https://github.com/OpenKH/XeEngine.Tools.Public
This will help to fix issue like #132
> Transfer XeEngine.Tools.Public repository reference to OpenKh

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
Also hid Build and Run if using Panacea on PC. Didnt hide run or stop even though it doesnt work on PC so the menu isnt one option hid build and run so build only is the first option for panacea. Main memory mentioned the possibility of making mod manager launch a shortcut for KH that you can make through epic games.
`com.epicgames.launcher://apps/4158b699dd70447a981fee752d970a3e%3A5aac304f0e8948268ddfd404334dbdc7%3A68c214c58f694ae88c2dab6f209b43e4?action=launch&silent=true`
but this shortcut would need to be consistent or a variable added so the end user can enable build and run through means the EGS already allows
> Edited mod manager for recent panacea PR to remove Bypass

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
So they dont have to check it every restart if they have panacea installed and wish to see both menus. Removed unnecessary Relay Command.
> Mod Manager now remembers if the user checked Dev View

- OpenKh.Research.Panacea/OpenKH.cpp
- OpenKh.Research.Panacea/OpenKH.h
- OpenKh.Research.Panacea/Panacea.cpp
These options will allow users to boot the 1.5+2.5 launcher directly to the game menu (`quick_menu=true`), or boot directly into one of the four games (`quick_launch=kh1, recom, kh2, or bbs`). The quick_launch option will be deleted by Panacea after use, so that you can run the games normally outside of the mods manager.
> Adding quick launch options to Panacea.

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
renamed the new __config Alios made to be _config2.
Pancea can now quick launch games in the KH 1.5 2.5 collection using a setting in panacea_settings.txt. added a dropdown only visible when Mods Manager is set to PC and the user has DevView enabled to allow launching any game in the collection quickly from Mod Manager. It is hidden by default but also kh2 by default since that the primary use for Mods Manager right now. If the user uses the EGS version when running either through run only or build and run pancea_settings.txt is read and quick_launch=`_quicklaunch` is appended to launch the chosen game kh2 by default. Unfortunately the Combo Box does now hide nice.
Added a menu for the user in setup wizard to check whether or not they use the EGS version of KH it is checked by default. If …
> Updates to utilize panacea changes.

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
Redid Alios' change to allow the wizard to run on an update. firstRunComplete is now wizardVersionNumber and if the new _wizardVersionNumber in MainViewModel.cs is greater than what is in mods-manager.yml the wizard is run again.
Moves Quick Launch option to its own menu that is now labeled so it is not a random dropdown box and also hide the Quick Launch Menu properly with no extra whitespace.
> Change FirstRun Variable and Quick Launch option

- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tests/Patcher/PatcherTests.cs
- docs/tool/GUI.ModsManager/index.md
Adds cmd as a possible type for listpatching via .yml files using the Mod Manager.
cmdList.yml files are setup exactly like TrsrList.yml files.
The ID of the command being edited as the "title", (this should match the ID of the command being edited) followed by the edits inside to change an actual command. In this example, the "Attack" command found in the command menu has its text changed to use the text for "Magic".
This should allow for compatibility between multiple different mods that change the cmd file.
> Add option to listpatch the cmd bar subfile in 03system.bin.

- .github/workflows/dotnet.yml
- build.ps1
This will enable auto build and release of .NET projects, and also panacea, in zip file.
Create 2 release tags:
- `latest`
- `release2-${{github.run_number}}`
Sample from: https://github.com/kenjiuno/OpenKh/releases
> Recover auto release with GitHub Action

- .github/workflows/dotnet.yml
Thus apply `continue-on-error: true` to `marvinpinto/action-automatic-releases@latest`
> Workaround for GitHub Actions `Error: Resource not accessible by integration`

- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
First commit is to better make sure mods are built if they match the launch game if it exists but not skip if its not exactly formatted. EX: it expects kh2 but if the mod maker types Kingdom Hearts 2 it wont skip it. Also moves the Launch Game Combo Box out of a sub menu and to the right.
Second is to seperate UIs for installed mods so the user only sees mods installed for the game the have chosen currently assuming the user installed the mod with the game they intended to use it with. This puts all mods in the mods folder into a subfolder with the games name and is not currently backwards compatible. Im not sure this second part code is done the best would like input.
> Mod Manger better launch game and making games "Seperate UI's"

- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tests/Patcher/PatcherTests.cs
- docs/tool/GUI.ModsManager/index.md
Adds enmp as a possible type for listpatching via .yml using the Mod Manager.
The enmp file controls various stats for enemies, like elemental resistances, battle level, and health.
Enmp listpatches are set up like this: 
Documentation on how to listpatch the enmp subfile & tests have also been included.
> [Mods Manager] Add enmp as valid listpatch method

- OpenKh.Patcher/PatcherProcessor.cs
JapaneseEvent & JapaneseSystem has different encoding results for some kanji, with some even not having any counterpart. Therefore, we need to add support for both types.
> Adds Japanese Event option to msg encoder

- OpenKh.Command.Bdxio/Models/BdxInstructionDesc.cs
- OpenKh.Command.Bdxio/Models/BdxInstructionDescs.cs
- OpenKh.Command.Bdxio/Utils/BdxDecoder.cs
- OpenKh.Command.Bdxio/Utils/BdxEncoder.cs
Support to encode/decode `pushImmf` instrument in bdscript.
Both `pushImm` and `pushImmf` are recognized same and work equally on BD VM.
Just bdx compiler/decompiler can recognize difference of `pushImm` and `pushImmf`.
e.g. diff
```patch
--- V:/OpenKh-bdx~/OpenKh.Tests.Commands/bin/Debug/net6.0/G_EB100/a.bdscript	Wed Nov  9 09:06:52 2022
+++ V:/OpenKh-bdx/OpenKh.Tests.Commands/bin/Debug/net6.0/G_EB100/a.bdscript	Sat Nov 26 20:19:52 2022
@@ -7,7 +7,6 @@
Addr: TR1
- Key: 0
Addr: TR0
-IsEmpty: false
Name: g_eb100
---
@@ -65,21 +64,21 @@
pushFromFSp 0
syscall 3, 38 ; ?
jnz L133
- pushImm 1065353216
+ pushImmf 1
syscall 0, 17 ; trap_random_getf (1 in, 1 out)
popToSp 4
pushFromFSp 4
- pushImm 1045220557
+ pushImmf 0.2
subf 
infzf 
jnz L131
pushFromFSp 0
pushImm 152
- pushImm 0
+ pushImmf 0 …
```
> bdscript: support pushImmf

- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Research.Panacea/OpenKH.cpp
- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/ModDetailsView.xaml
Change all instances of "recom" to "Recom" as the other games were named based of their PKGs. Since Recom only has the one PKG Recom with no first, second, etc.
Updated Panacea also to expect Recom.
Updated the setup wizard to not only look for the extracted data folder for Recom and bbs but a folder within so the game needs to be extracted to allow progress.
Fixed changing setup wizard from an emulator setup to a PC setup going to the ISO page after selecting the location of the installed EGS game
Changed local mod text to Segoe with italics instead of semibold
> Mod Manager Fixes

- OpenKh.Tools.BbsMapStudio/OpenKh.Tools.BbsMapStudio.csproj
- OpenKh.Tools.Common.CustomImGui/OpenKh.Tools.Common.CustomImGui.csproj
- OpenKh.Tools.Kh2MapStudio/OpenKh.Tools.Kh2MapStudio.csproj
- OpenKh.Tools.LayoutEditor/OpenKh.Tools.LayoutEditor.csproj
Reverts OpenKH/OpenKh#739
It seemed like the problems were solved as it said it was able to build but in fact it skipped building the layout editor as the three errors still exists so this needs to be reverted. My bad
> Revert "Bump ImGui.NET from 1.78.0 to 1.89.2"

- OpenKh.Kh2/SystemData/Sklt.cs
Game files use -1 when a character doesnt use a Bone 1 or 2 to hold a weapon so Bone 1 and 2 need to be shorts not ushorts
> Fix sklt listpatching.

- OpenKh.Patcher/PatcherProcessor.cs
Some hitboxes share the same ID but use different SubID's, causing issues when only checking the Id of a hitbox.
> Fix atkp listpatching by checking both Id & SubId

- OpenKh.Kh2/Battle/Magc.cs
Made FinishMotion a ushort instead of short as the game uses 65535 for magnet and cure finish motion for some reason.
> Fixed Magc List Patch

- build.ps1
Currently build error of OpenKh tools are treated as _successful_, and then GitHub Actions recognize `.NET / build (pull_request)` pipeline succeeded.
This behavior is wrong.
The build error should make `.NET / build (pull_request)` pipeline failure.
As a result, it prevents admins from merging broken commits accidentally.
In this pr, allow `dotnet publish` to emit success/error code correctly.
`Error: Process completed with exit code 1.` will be logged at end of the build step log, if there is a build error.
> Allow `dotnet publish` to emit success/error code correctly

- OpenKh.Kh2/ModelTexture.cs
- OpenKh.Tools.Kh2MdlxEditor/Utils/ImageUtils.cs
- OpenKh.Tools.Kh2MdlxEditor/ViewModels/Main2_VM.cs
- OpenKh.Tools.Kh2MdlxEditor/ViewModels/TextureFile_VM.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/TextureFile_Control.xaml
- OpenKh.Tools.Kh2MdlxEditor/Views/TextureFile_Control.xaml.cs
Images shown in the MDLX Editor can now be exported.
There's code (Written but hidden in the view) for adding/removing textures, however the textures are created from the data. Since the actual data remains the same, the output file will remain the same. This'll only work if the textures are changed in the actual data, for which there's no code as of now.
> MdlxEditor - Export Images

- OpenKh.Tools.ModsManager/Services/OpenkhUpdateCheckerService.cs
- OpenKh.Tools.ModsManager/Services/OpenkhUpdateProceederService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- Use first line of `openkh-release` instead of entire file. Because the local release tag file `openkh-release` is suffixed by `\n`.
```sh
$ hexdump.exe -C openkh-release
00000000  72 65 6c 65 61 73 65 32  2d 34 33 36 0a           |release2-436.|
0000000d
```
- Fix that ModsManager cannot be re-launched after update if full path of `OpenKh.Tools.ModsManager.exe` contains at least one space.
- Display "The latest version '{checkResult.CurrentVersion}' is already installed!" when update is not required.
> Fix updater errors of OpenKh.Tools.ModsManager

- OpenKh.Research.Panacea/dllmain.cpp
This PR, similar to #784, allows Panacea to hook to the game using "version.dll".
This hook is necessary to allow Panacea to play more nicely with WINE, improving Linux and Steam Deck support for the mod loader. 
An added side effect is that "version.dll" also hooks with "EOSSDK-Shipping-Win64.dll". This does not seem to interfere with operation as Panacea will automatically hang itself up, but whether or not the project is okay with this DLL hooking to an EGS dll is a question to ask.
Like before, this pull request will remain in draft until maintainers have had a chance to test or present questions.
> Panacea Hooking Support: VERSION.DLL

- OpenKh.Tools.LayoutEditor/Dialogs/SpriteEditDialog.cs
When it was broken:
- 434ed0b4cef899e85c2f9124c878b859f05993b2 Good
- e5ac7c1563c439ce648be8199ae5c9e2e1cc6b76 Broken
At 434ed0b4cef899e85c2f9124c878b859f05993b2:
At latest:
With this workaround:
> Workaround to avoid that wrong preview sprite is shown on Sprite editor in OpenKh.Tools.LayoutEditor

- OpenKh.Engine.MonoGame/MonoSpriteDrawing.cs
Before:
After:
---
`SurfaceFormat` that RenderTarget2D uses in default is `Color`.
https://github.com/MonoGame/MonoGame/blob/b21463b419e55b4c898030fc22bee77dabb11210/MonoGame.Framework/Graphics/RenderTarget2D.cs#L65-L66
https://docs.monogame.net/api/Microsoft.Xna.Framework.Graphics.SurfaceFormat.html
> Color	
> Unsigned 32-bit ARGB pixel format for store 8 bits per channel.
I'm not sure whether this means that the byte order is `AA RR GG BB` or not.
Fix #825
> Fix a swapping problem of R and B channels on OpenKh.Engine.MonoGame

- OpenKh.Kh2/Models/ModelSkeletal.cs
- OpenKh.Tools.Kh2MdlxEditor/ViewModels/ModelBones_VM.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/Main2_Window.xaml
- OpenKh.Tools.Kh2MdlxEditor/Views/Main2_Window.xaml.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/ModelBones_Control.xaml
- OpenKh.Tools.Kh2MdlxEditor/Views/ModelBones_Control.xaml.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/Model_Control.xaml.cs
Adds a page to edit the bones. This includes editing their translation as well as adding new bones if wanted (Beware of mset bone count)
Opened by right clicking the model icon (sphere)
Note: The Flags column is added just in case it's needed, I haven't bothered with implementing its decoding/encoding. The bitmap goes like this:
terminate
below
enableBias
reserved [19]
undefined [10]
> MdlxEditor bones edition

- OpenKh.Kh2/Models/ModelSkeletal.cs
Fixes a bug during saving MDLX files which calculates the incorrect offset / ModelHeader size, causing subsequent loads to be corrupted. A x4 multiplier seems to have been forgotten here.
In general, this issue does not necessarily occur frequently, because for it to occur your last mesh needs to have more than 4 bones. If it has 4 bones or less, then the multiplication by 4 is within the rounding-margin of 16 bits, which will not trigger the problem.
To reproduce the problem on master, load any MDXL (I recommend P_EX100), save it as an .fbx . Then edit the fbx and remove the two small meshes (crown and necklace) so you're left with the two big meshes. Re-import this .fbx into the main model (keep shadows). Save this new .mdlx (a copy of this mdlx is attached to this issue).
Set a …
> Multiply the BoneMatrix count by the same value as when updating groups

- OpenKh.Imaging/PngImage.cs
Fix png loader of OpenKh.Imaging.PngImage: crash when tRNS (transparency or alpha) chunk is missing on indexed image.
`OpenKh.Tools.ImageViewer` is one of affected tools.
> Fix png loader of OpenKh.Imaging.PngImage

- OpenKh.Research.Panacea/OpenKh.Research.Panacea.vcxproj
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
with error handling to prevent a partial panacea install causing the game to crash.
If Panacea is missing files it will remove Panacea and any partially installed dlls and you will be unable to use the mod loader. Otherwise install works normally. Checksum is still only calculated for Panacea not these dlls.
this adds an additional 13 dlls that Panacea needs to the game install folder. The remove command will remove all 13 + Panacea dlls
> Mod Manager update for new panacea 

- OpenKh.Tools.Kh2ObjectEditor/Services/MdlxService.cs
When saving an MDLX, the app was overwriting the existing files, leading to possible errors and larger sizes if the file being overwritten was larger than the new file being written. Now it'll create the files from scratch.
> Kh2ObjectEditor - File overwrite fix

- OpenKh.AssimpUtils/Kh2MdlxAssimp.cs
- OpenKh.Kh2/Models/ModelCommon.cs
- OpenKh.Kh2/Models/ModelSkeletal.cs
- OpenKh.Kh2/Models/VIF/DmaVifPacket.cs
- OpenKh.Kh2/Models/VIF/VifPacket.cs
- OpenKh.Kh2/Models/VIF/VifProcessor.cs
- OpenKh.Ps2/VpuPacket.cs
Adds vertex color support to the MDLX builder.
> MDLX builder vertex colors

- OpenKh.Kh2/Sequence.cs
- OpenKh.Tools.LayoutEditor/AppSequenceEditor.cs
- OpenKh.Tools.LayoutEditor/Dialogs/SpriteEditDialog.cs
- OpenKh.Tools.LayoutEditor/Dialogs/SpriteGroupEditDialog.cs
> Add a way to add Sprites in the Layout Editor [SEQUENCE]

- OpenKh.Tools.Kh2MdlxEditor/Utils/Viewport3DUtils.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/Viewport_Control.xaml.cs
- OpenKh.Tools.Kh2ObjectEditor/Utils/ViewportHelper.cs
In WPF texture UVs (Which go from 0 to 1) take 1 as the highest value in the mapping list, meaning meshes that don't have UVs that go from 0 to 1 would render incorrectly (Thanks WPF)
Whenever the model is rendered in WPF a couple of dummy vertices are added with UVs 0,0 and 1,1 so the mapping scales correctly, which fixes the issue. Now all models should be rendered accurately.
> UV mapping fix

- OpenKh.Kh2/Models/VIF/VifProcessor.cs
When implementing vertex coloring, it was enforced accidentaly. If the model didn't have vertex coloring the app would throw an error. Changed it so that vertex color is only applied if all the vertices have vertex coloring.
> Mdlx Builder - Fix import if no vertex colors

- OpenKh.Tools.ModsManager/Exceptions/Exceptions.cs
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
In case it partially installed or has been edited and they want to install fresh. They do not have to remove the mod then install can just reinstall. Very helpful if a partial mod install happened because sometimes the mod didn't show up in mod manager so you had to go into the `mods` folder and delete it.
Zip
GitHub
No Click
Yes proceeds like normal after deleting the old mod install.
> Gives user the option to overwrite old mod install.

- OpenKh.AssimpUtils/Kh2MdlxAssimp.cs
- OpenKh.Kh2/Models/ModelCommon.cs
- OpenKh.Kh2/Models/ModelSkeletal.cs
- OpenKh.Kh2/Models/VIF/DmaVifPacket.cs
- OpenKh.Kh2/Models/VIF/VifCommon.cs
- OpenKh.Kh2/Models/VIF/VifPacket.cs
- OpenKh.Kh2/Models/VIF/VifProcessor.cs
- OpenKh.Kh2/Models/VIF/VifUtils.cs
- OpenKh.Ps2/VpuPacket.cs
- OpenKh.Tools.Kh2MdlxEditor/Utils/MdlxEditorImporter.cs
- OpenKh.Tools.Kh2MdlxEditor/ViewModels/Importer_VM.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/Importer_Window.xaml
- OpenKh.Tools.Kh2MdlxEditor/Views/Importer_Window.xaml.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/Main2_Window.xaml
- OpenKh.Tools.Kh2MdlxEditor/Views/Main2_Window.xaml.cs
Behold! The last MDLX importer update! (I hope)
* The VIF code has been updated and it now should reflect the data more accurately.  This seems to have fixed an issue with the previous importer release.
* The importer now supports vertex normals.
* Vertex colors and normals can be selected to be applied per mesh.
* New buttons have been added to open a file by selecting it instead of drag & dropping and to save over the opened MDLX.
* If I have to touch this again I'm gonna jump out the window.
When importing, the user can either select the file or drag and drop it. Once the file is loaded the list of meshes will appear. For those meshes that have colors or normals, their checkbox will be able to be checked to import the colors or normals. Once everything's set, clicking in Import will …
> Vertex normals, Vif code update and MDLX importer update

- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
With my recent PR to allow users to overwrite a mod if they try to install the mod again (for purposes of overwriting a partial installation or adding a new rando seed) it would always call `ReloadModsList()` making it so if you were installing a mod for the first time it would get kicked to the bottom of active mods. This fixes that to only reload mods list when overwriting an old mod so the user can easily enable and move the mod in priority without needing to scroll to the bottom of their list and find the mod they installed.
> When installing a mod only reload mods list if you are overwriting an old mod of the same name

- OpenKh.Tools.ModsManager/Services/ModsService.cs
In my testing it would fairly often be behind the other windows making MM seem like it was frozen.
This now makes sure the window appears in front when it pops up.
> Forces the window asking the user if they wish to overwrite a mod to the front.

- OpenKh.Research.Panacea/OpenKh.Research.Panacea.vcxproj
- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml
- OpenKh.Tools.ModsManager/Views/InstallModView.xaml.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml.cs
- OpenKh.Tools.ModsManager/Views/PresetsWindow.xaml
- OpenKh.Tools.ModsManager/Views/PresetsWindow.xaml.cs
Took everything from Lua Engine PR into its own. I believe this is better to have in main and once Lua Engine is ready it will be merged by itself. will copy relevant info from mention PR below.
Add Presets and Lua Script install.
~~When saving a new preset you will need to restart mod manager for the preset to show under Load Presets.~~ If you save a preset with the same name as one that already exists it will override the previous preset. If you try to include characters in the name that windows does not let be in a filename it will automatically be replaced by +.
Taken from osdanovas PR to my fork.
Changes the presets to its own menu. Backend remains mostly the same.
Can also install a Lua Script directly into mod manager as an easy way to enable or disable them.
When you install a …
> Presets and Lua Script install.

- OpenKh.Tools.ModsManager/Services/OpenkhUpdateProceederService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
Delete the downloaded zip for the update from temp AppData after extracting it. 
Add more lines to the .bat. Sometimes window?.close() fails to close Mod Manager because window is null so the bat will try also before doing anything. If MM is alreaddy closed the bat just continues to execute as normal. After starting the updated MM deletes the extracted openkh download then itself. 
Preset window changed to ShowDialog() so you cannot mess with the main window while the preset window is open. 
Moved Check for update to the settings tab.
> Various changes.

- OpenKh.Tools.ModsManager/Services/ModsService.cs
Turns out the metadata can be surrounded by ' or ". This may be overkill but it shoudnt fail to install a Lua Script again.
> Lua Script Install Bugfix

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/ModManagerView.xaml
ToolTips for the MoveUp, MoveDown, AddModCommand, and RemoveModCommand.
Changed instances of ReloadModsList() to only do whats needed when possible. If not possible FetchUpdates after ReloadModsList() so the updates do not get hidden until a Mod Manager restart.
> Fixed Mod Updates being hidden and added ToolTips for 4 buttons on Mod Manager main window

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
This does take a portion of setup wizard code from #867 just added a little more detection for an edge case if files with both names are found somehow.
New commit adding check for mods update command so the user doesnt need to restart MM to check mods for updates if they are not showing.
> Proper version.dll support in mod manager and preset save fix.

- OpenKh.Tools.Kh2MsetEditor/ViewModels/Transfer_VM.cs
- docs/kh2/file-type.md
- docs/kh2/file/type/12soundinfo.md
- docs/kh2/file/type/scd.md
- docs/kh2/notable-files.md
Some more comprehensive documentation on the SCD format for KH2. The knowledge here is probably identical for the other games that use SCD, but this is untested.
This updated SCD documentation includes some info I haven't found anywhere else, like the Sound Mapping Table that maps sound effects to ID's to be used by the game, as well as controls the volume of each sound, as well as an int in the SoundEntry table that controls how long audio should play for.
Also includes documentation on 12soundinfo.bar, this is a file that controls various ambient sound effects in KH2's maps like footsteps and environmental sounds on a per-room basis.
> Documentation of KH2 SCDs & 12soundinfo.bar.

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
To either uninstall or allow the user to easily reinstall in case the toml is messed up somehow
Also changes the way the PC extract game data stores which games to extract to a list from a bool per game/checkbox
> Add a uninstall button for Lua Backend 

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
If during config of a pre-existing LuaBackend.toml MM detects a possible path to another MM (even if it is the same MM) displays a message box asking to overwrite it.
> Lua Backend Configure Actual Error Handling

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/ModViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/ModDetailsView.xaml
- OpenKh.Tools.ModsManager/Views/ModManagerView.xaml
Add a button above MoveSelectedModUp to move selected mod to be first in the list/highest priority so you dont have to spam click if you have many mods installed
> Move Selected Mod Top Button

- OpenKh.Imaging/PngImage.cs
- OpenKh.Tools.Kh2MdlxEditor/Utils/ImageUtils.cs
- OpenKh.Tools.Kh2MdlxEditor/Utils/MdlxEditorImporter.cs
- OpenKh.Tools.Kh2MdlxEditor/Views/Main2_Window.xaml.cs
Fix a bug of PNG file loader. And also adding some exception handling things
> Fix a bug of PNG file loader. And also adding some exception handling things

- OpenKh.Research.Panacea/OpenKH.cpp
- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
also changes panacea from looking for `ddd` to `kh3d` since thats what the pkgs are named.
> Mm DDD support

- OpenKh.Tools.LayoutEditor/AppSequenceEditor.cs
`Sprite group edit` popup now opens _independently_ on selection: `Edit` → `Sprite groups...`
> Fix Sprite Groups window won't be opened.

- OpenKh.AssimpUtils/AssimpGeneric.cs
- OpenKh.AssimpUtils/Kh2MdlxAssimp.cs
- OpenKh.AssimpUtils/OpenKh.AssimpUtils.csproj
- OpenKh.Tools.Kh2MdlxEditor/Views/Main_Window.xaml.cs
- OpenKh.Tools.Kh2MsetMotionEditor/App.cs
- OpenKh.Tools.Kh2MsetMotionEditor/OpenKh.Tools.Kh2MsetMotionEditor.csproj
- OpenKh.Tools.Kh2MsetMotionEditor/Usecases/InsideTools/MdlxMsetLoaderToolUsecase.cs
- Added a feature in the Monogame GUI of MsetMotionEditor to export the selected animation binary into an animated FBX. 
- I will add a feature to export all at once later. 
- I made a method static in Main_Window.xaml.cs in order to use it without copy-pasting it in the MsetMotionEditor code. This method remains unchanged.
> Export ANB into animated FBX.

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
without changing the selected collection first if you also just selected the proper filepath to the collection for the first time.
> Fix Lua Backend Config checkboxes not showing up

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
Added option to automatically detect game installation folders during Mod Manager setup wizard. Users can choose to click a button that will auto populate the folder directories during setup (if they exist). Can only find KH1.5+2.5 and KH2.8 installations from Epic Games Store.
> Automated Installation Detection for Mod Manager 

- OpenKh.Common/Log.cs
- OpenKh.Tools.ModsManager/App.xaml.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/ModViewModel.cs
The detail error message of install/update mods will be logged into file `OpenKh.Tools.ModsManager.log`.
It is flushed at app exit.
> Add detail error logging for installing or updating mods

- OpenKh.Tools.ModsManager/Models/ViewHelper/ActionCommand.cs
- OpenKh.Tools.ModsManager/Views/NotepadVM.cs
- OpenKh.Tools.ModsManager/Views/NotepadWindow.xaml.cs
- OpenKh.Tools.ModsManager/Views/SelectModTargetFilesVM.cs
- OpenKh.Tools.ModsManager/Views/SelectModTargetFilesWindow.xaml
- OpenKh.Tools.ModsManager/Views/SelectModTargetFilesWindow.xaml.cs
- OpenKh.Tools.ModsManager/Views/YamlGeneratorVM.cs
- OpenKh.Tools.ModsManager/Views/YamlGeneratorWindow.xaml
- OpenKh.Tools.ModsManager/Views/YamlGeneratorWindow.xaml.cs
Mainly 2 changes. I completely forgot to commit to my git repository which should be applied to #959:
Add some help messages to UI.
Move business logic from `YamlGeneratorVM.cs` to `YamlGeneratorWindow.xaml.cs`
At the time 77b3b9df8dc4d6df478d6039d659c6576e4c021a, the coding style is like the following figure:
- _Business logic_ is like: when I click the search button, YamlGenerator will look for files having entered keywords.
- _DataBinding variables_ are like: bi directional storage to load/save the content directly associated with UI component. e.g. text to store search keywords entered by user. `public string SearchKeywords { get; set; }`
The problematic thing is that UI brings tons of _chain reactions_.
Imagine, if I merge both of _DataBinding vairables_ and _business logic_ into one …
> Fix YamlGenerator in ModsManager

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
The detail error message of launcher error is displayed and logged.
displayed:
logged into `OpenKh.Tools.ModsManager.log`:
Be careful! the log file is always cleared whenever we start the ModsManager.
> Add logging on launcher error especially without `Launch via Epic Games` option checked.

- OpenKh.Patcher/PatcherProcessor.cs
Made sure when listpatching ATKP that it checks the Switch field as well. Having the wrong Switch field can break a move and certain duplicate entries will use Switch to distinguish between each other
> Fixed unreachable atkp ids when listpatching

- OpenKh.Tools.ModsManager/Services/OpenkhUpdateProceederService.cs
- Use `chcp 65001` instruction: cmd.exe accepts UTF-8.
- Use `robocopy` instead of `xcopy`. It won't allow to skip copy of files. So it is more stable way for update purpose.
> Improve update batch of ModsManager:

- OpenKh.Tools.Kh2MapStudio/App.cs
- OpenKh.Tools.Kh2MapStudio/MapRenderer.cs
Added camera controls to move up (Shift) and down (Left Ctrl)
Changed the box opacity to 0.3 to be able to see the entities contained within.
> Kh2 MapStudio - Up down camera controls and reduced box opacity

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
Added the option for Steam Installation Files!
It can auto detect directory
Mapped based on the .VDF of the libraries configured on Steam, so if the app is installed, this will find it in any directory.
Tested:
- Auto Detect Files
- Extract Game Data
Changes:
- Modified in the .xml a new option to the list.
- Modified obligatory find the "EOSSDK-Win64-Shipping.dll".
- Added 3 variables, "PcReleaseSteamLocation", "PcReleaseSteamLocationKH3D", "PcReleaseLanguageDT"; Steam in my case download as language the folder dt (IDK if its the case for anyone).
- Logic based on the 3 variables, nullish logic for detect location and assign the right variable.
*All tested with KH3D
Also this may mitigate issue of [#1056](https://github.com/OpenKH/OpenKh/issues/1056)
Output Succesfull:
> Fixing Not Available Steam Files for Mod Manager

- OpenKh.Kh2/BinaryArchive.cs
- OpenKh.Tools.Kh2ObjectEditor/Classes/MotionSelector_Wrapper.cs
- OpenKh.Tools.Kh2ObjectEditor/Classes/Object_Wrapper.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Motions/ModuleMotions_Control.xaml.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Motions/ModuleMotions_VM.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Motions/MotionRenameWindow.xaml.cs
- OpenKh.Tools.Kh2ObjectEditor/Services/AttachmentService.cs
- OpenKh.Tools.Kh2ObjectEditor/Services/ClipboardService.cs
- OpenKh.Tools.Kh2ObjectEditor/Services/MsetService.cs
- OpenKh.Tools.Kh2ObjectEditor/ViewModel/ModuleLoader_VM.cs
- OpenKh.Tools.Kh2ObjectEditor/ViewModel/Viewport_ViewModel.cs
The Bar class doesn't handle file linking in a way that could be easily modified. Modifying this behaviour would lead to changing the whole structure so I made a new class.
Loads every entry with its offset, duplicate flag (Index) and a copy of the subfile it is pointing to. When rebuilding it stores the subfiles in a dictionary using as key the Name and Type of the file. When a duplicate flag (Index 1) is detected it searches for the subfile's offset in the dictionary.  Note that this means duplicate files must use the same name as the original otherwise an error is thrown.
Loads every subfile and then every entry with a link to its subfile. When rebuilding it writes the existing entries and linked subfiles so there's no room for error. Dummy entries' offsets are also set to -1, which …
> BinaryArchive class

- OpenKh.Tests.ModsManager/GameDataExtractionServiceTest.cs
- OpenKh.Tests.ModsManager/OpenKh.Tests.ModsManager.csproj
- OpenKh.Tools.ModsManager/Services/GameDataExtractionService.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
- OpenKh.sln
This fix can continue the extraction process after the failed file without retrying the entire process.
`Yes | No | Cancel`
- Yes: retry at the failed file
- No: skip the failed file
- Cancel: abort the extraction process
Fix #1066
> Improve game data extraction process

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
Also trying new _pcReleaseLanguage based on responses in the discord the only valid folders for pks to be in are
EGS-JP will be in a folder named `jp`
EGS-Global (Everything else_ will be in a folder named `en`
Steam will be in a folder named `dt` (regardless of jp version or not)
> Fixes Run Shortcut for EGS and Steam

- OpenKh.AssimpUtils/Kh2MdlxAssimp.cs
- OpenKh.AssimpUtils/OpenKh.AssimpUtils.csproj
- OpenKh.Tools.Kh2ObjectEditor/Modules/Motions/ModuleMotions_Control.xaml
- OpenKh.Tools.Kh2ObjectEditor/Modules/Motions/ModuleMotions_Control.xaml.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Motions/ModuleMotions_VM.cs
- OpenKh.Tools.Kh2ObjectEditor/Views/Main_Window.xaml
- OpenKh.Tools.Kh2ObjectEditor/Views/Main_Window.xaml.cs
Added options to export the model (Top menu) and the animations (Right click/Contextual menu on motions)
Notes on animation exporting:
- Due to IKs there's no way to export animations by keys, instead the transformation matrices are calculated using the Kh2Anim library.
- Due to the amount of keys exported the animations can't be imported back unless edited to reduce the key count. Note that there's no error message for this, the animation will simply not change when this occurs.
- The animations look right in Blender but in Noesis it'll look messed up. I think this could be fixed by adding the "CustomFrameRate" metadata but Assimp refuses to export Metadata.
- Similar to the previous point, Assimp sets all scaling keys to 1 for some reason so scaling can't be exported.
> Kh2ObjectEditor - Export model and animations

- OpenKh.Tools.ModsManager/Views/MainWindow.xaml
- OpenKh.Tools.ModsManager/Views/MainWindow.xaml.cs
Ready to merge after #1078
This adds a `Frequently Asked Questions` button to the mod manager under the `Info` menu, which will link to a page on the site
> Add FAQ button to the mod manager

- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
The orignal message was mean for an ISO extraction. Extraction PC version is longer due to remastered assets and also there are 5 supported games so the PC version now has its own message instead and the old one only shows for emulator.
PC Extraction page msg
Old msg for an ISO extraction
> Update extraction time msg.

- OpenKh.Tools.ModsManager/App.xaml
- OpenKh.Tools.ModsManager/Styles/MonoStyleCheckBox.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
On light mode (proposed)
On light mode (current)
On dark mode (proposed)
On dark mode (current _without workaround_)
WPF's default CheckBox style is well designed for native Windows light mode.
This may not be fit on our dark theme ↓
Currently one workaround is needed to apply dark mode on our WPF apps. 
```cs
<Window.Resources>
<Style TargetType="CheckBox">
<Setter Property="Foreground" Value="{Binding ColorTheme.TextColor}"/>
</Style>
</Window.Resources>
```
About the design of check mark `X`, this is directly taken by sample of MSFT site: [CheckBox Styles and Templates - WPF .NET Framework | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/checkbox-styles-and-templates?view=netframeworkdesktop-4.8).
This pull request proposes to apply this alternative …
> Apply an alternative CheckBox default style to ModsManager

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
Allow mod manager to launch each of the 5 supported games directly when using steam.
If the game is installed on steam and you make a text file in the game install folder named `steam_appid.txt` with the contents being the appid of the launcher you can launch the games exes directly.
contents of the 1.5 2.5 .txt
contents of the 2.8 .txt
for any curious reader this does also work for 0.2 but it needs to be next to the 0.2 exe which is in a folder further down the heiarchy for my personal install its inh `D:\SteamLibrary\steamapps\common\KINGDOM HEARTS HD 2.8 Final Chapter Prologue\KINGDOM HEARTS 0.2 Birth by Sleep\Binaries\Win64` uses the same appid as the 2.8 one for DDD its just the 0.2's exe is in a different location
> Steam API trick

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml.cs
Remove old `PcReleaseLanguage` in setup wizard for new `PCReleaseLanguage from my last PR.
This also fixes trying to extract from `en` instead of `jp` when Japanese EGS version is selected if user doesnt restart the setup wizard after selecting those options. Also fixes SteamAPITrick setup wizard page showing when steam is not selected.
> Fix using English Filepath when extracting Japanesse version and SteamAPITrick wizard page showing improperly

- OpenKh.Kh2/DpdVsf.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectDpdVoice.xaml
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectDpdVoice.xaml.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectDpdVoiceList_Control.xaml
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectDpdVoiceList_Control.xaml.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectDpdVoice_VM.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectsDpdTabs_Control.xaml
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectsDpdTabs_Control.xaml.cs
Added Effect VSF list support to Kh2ObjectEditor, although I have no idea what the file does.
> Kh2ObjectEditor - Added effect VSF list to the editor

- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
to fix mod manager from preventing people who only set up mod manager for KH3D from being able to extract game data since it tries to extract KH2
> Remove KH2 as default game to extract 

- OpenKh.Egs/OpenKh.Egs.csproj
- OpenKh.Imaging/OpenKh.Imaging.csproj
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
Some developers reported about `DotNetZip` in community discord.
It is now deprecated (not updatable anymore) and they say it displays a vulnerable status on JetBrains Rider IDE.
[NuGet Gallery | DotNetZip 1.16.0](https://www.nuget.org/packages/DotNetZip)
Remove the `DotNetZip` dependency.
Zlib decompression is still needed for the PNG image decoder.
So import `Iconic.Zlib.Netstandard` and I'm going to resolve this situation.
> Remove dependency of `DotNetZip`.

- OpenKh.Kh2/Messages/Internals/JapaneseEventDecode.cs
- OpenKh.Kh2/Messages/Internals/JapaneseSystemDecode.cs
- OpenKh.Patcher/BarEntryExtractor/ProvideExtractorsService.cs
- OpenKh.Tools.ModsManager/ViewModels/ModViewModel.cs
- OpenKh.Tools.ModsManager/Views/YamlGeneratorWindow.xaml.cs
Fix ModsManager crashes on startup when `mod.yml` is empty file.
Fix Generator of YamlGenerator fails due to null error, if mod.yml is an empty file.
Fix error `System.NotImplementedException: Command 17 not implemented yet` when trying to decode Japanese evt/sys messages.
Fix problems of ProvideExtractorsService:
- Remove redundant `await Task.Yield();`
- Valid file path to msg.yml is now set:
```
- name: msg/jp/sys.bar
method: binarc
source:
- name: sys
method: kh2msg
source:
- name: msg/jp/sys_sys.yml
language: jp
type: list
```
- Japanese evt messages are now set to `je` like `language: je`:
```
- name: msg/jp/al.bar
method: binarc
source:
- name: sys
method: kh2msg
source:
- name: msg/jp/al_al.yml
language: je
type: list
```
> Fix some YamlGenerator (ModsManager) inconvenience

- OpenKh.Patcher/Metadata.cs
- OpenKh.Patcher/PatcherProcessor.cs
Adding comments to entities around the patching process.
Adding an `exclusiveLock` to `PatcherProcessor.Patch` so that it can accept any writable IDictionary (non-ConcurrentDictionary) instance.
> Adding comments to entities around patching process and

- OpenKh.Patcher/PatcherProcessor.cs
for the same file when said `assetFile` has a `multi:`
> Fix multiple warnings

- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
If the user had a folder with the same name as where 1.5 2.5 or 2.8 were installed it would say it is a valid install even if the folder is empty. this checks that .dll that lets you press the next button exists in that folder first.
> Better Detect Install for Steam

- OpenKh.Tools.ModsManager/Services/ModsService.cs
previously pcpatches could only be installed if the file extension was all lowercae. this uses ToLower() on the string check to fix that
> pcpatch installation fix

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/SetupWizardViewModel.cs
- OpenKh.Tools.ModsManager/Views/SetupWizardWindow.xaml
Move any ConfigurationService Variable that was previously only set by clicking `Finish` at the end of the setup wizard to when the actual variable is chosen.
EX: when selecting the path for PC 1.5 2.5 if its valid sets the path in ConfigurationService also.
This prevents users from closing mod manager setup wizard without saving the things they changed
Better error msg if a game install isnt found.
Suggest verifying your game files because if mod manager doesnt find the files it wants it will say a game install doesnt exist.
> Setup Wizard Changes

- OpenKh.Kh2/Dpd.Texture.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectDpdTexture_Control.xaml
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectDpdTexture_Control.xaml.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectDpdTexture_VM.cs
To coincide with #1151, DPD textures will now be displayed in the order they're meant to be ordered in-game, and will denote when they're part of a combo-texture like so:
> [KH2 Object Editor] Add "Export all as PNG" & adjusted DPD texture order display

- OpenKh.Kh2/SystemData/Item.cs
- OpenKh.Patcher/PatcherProcessor.cs
- docs/tool/GUI.ModsManager/creatingMods.md
Addresses #1129.
Adds "InsertBefore" and "InsertAfter" tags that can be used in item listpatching. This tag is set to 0 by default, and if not included in a YML, files will simply append to the end like before, maintaining backwards compatibility with current mods.
Example of usage:
````Items:
- Id: 9999
Type: Consumable
Flag0: 0
Flag1: 40
Rank: C
StatEntry: 1
Name: 33528
Description: 33529
ShopBuy: 40
ShopSell: 10
Command: 23
Slot: 0
Picture: 1
Icon1: 9
Icon2: 0
InsertBefore: 7
- Id: 10000
Type: Consumable
Flag0: 0
Flag1: 40
Rank: C
StatEntry: 1
Name: 33528
Description: 33529
ShopBuy: 40
ShopSell: 10
Command: 23
Slot: 0
Picture: 1
Icon1: 9
Icon2: 0
InsertBefore: 9999
- Id: 10001
Type: Consumable
Flag0: 0
Flag1: 40
Rank: C
StatEntry: 1
Name: 33528
Description: 33529
ShopBuy: 40
ShopSell: …
```
> [ModManager] Add "InsertBefore" and "InsertAfter" tags for item listpatching

- OpenKh.Command.MapGen/Models/MapGenConfig.cs
- OpenKh.Command.MapGen/Models/MaterialDef.cs
- OpenKh.Command.MapGen/Utils/FlattenCollisionBuilderAlt.cs
- OpenKh.Command.MapGen/Utils/MapBuilder.cs
- docs/tool/CLI.MapGen/index.md
This adds an alternate type of collision builder, based on FlattenCollisionBuilder. When used, this will split the generated collision in the collisionMesh part of the COCT so that each face becomes its own mesh. Then, you can choose to assign specific faces to a material and under the materials section, you can assign these faces a `group` value, so that this collision can be toggled on and off in-game using the MapVisibility command inside the ARD. This is how the game makes temporary barriers for forced fights.
Example of its usage:
```
disableBSPCollisionBuilder2: true
materials:
- name: 'Wall' #Wall (COLLISION)
ground: 0
surfaceFlags: 0x811
group: 3
```
> [Mapgen] Add "disableBSPCollisionBuilder2" option for mapdef.yml

- OpenKh.Patcher/PatcherProcessor.cs
Small tweak to objentry listpatching to sort newly added entries by ID before then patching them in. 
The game requires entries in objentry to be in numerical order, and will refuse to load in entries that don't adhere to this order.
Example being, Mod A listpatches an ID of 5000, and Mod B listpatches an ID of 4562.
If Mod A has lower priority than Mod B, then ID 5000 would be appended to objentry first, followed by the id of 4562. This means that any ObjID's lower than 5000 that get built after Mod A would fail to load in-game. In order for these two mods to work together, Mod A would need to be placed at a higher priority than Mod B.
Sorting by IDs first fixes this issue, as regardless of order, 4562 would be appended first, followed by 5000.
> [Mod Manager] Adjust objentry listpatching

- OpenKh.Kh2/Pax.cs
- OpenKh.Kh2/Utils/BitFlag.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/AI/ModuleAI_Control.xaml
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectElements_Control.xaml
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectElements_Control.xaml.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectElements_VM.cs
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectElements_Wrapper.cs
- OpenKh.Tools.Kh2ObjectEditor/OpenKh.Tools.Kh2ObjectEditor.csproj
- OpenKh.Tools.Kh2ObjectEditor/Utils/Property_Util.cs
Adds the Effect Caster flags and allows returns in AI edit menu.
Note: Due to wrapping Effect Casters now have to be saved. A button has been added for that as well.
> Kh2ObjectEditor - Effect caster flags and allow returns in AI edit

- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectElements_Control.xaml
- OpenKh.Tools.Kh2ObjectEditor/Modules/Effects/M_EffectParticles_Control.xaml
Simple fix to allow editing these 2 fields. They being read only was probably a copy-paste error.
> Kh2ObjectEditor - Fix - Allow editing particle effect ids

- OpenKh.Command.MapGen/Utils/MapBuilder.cs
- OpenKh.Kh2/ModelTexture.cs
Adds logic to MapBuilder.cs to correctly swap the MIN/MAX values for the CLAMP register's U and V coordinates.
Fixes a bug in the ModelTexture constructor where the footerData was not being processed, causing the texture footer to be omitted from the final file.
> Fix mapgen texture scrolling

- OpenKh.Command.AnbMaker/Utils/Builder/InterpolatedMotionBuilder.cs
Changes interpolation type to linear for smoother animations (hermite shouldn't be used with anbmaker ever) and reduces the frequency of out of bounds errors for values by rounding them to 3 decimal places. There's no noticeable visual difference between 5.3459 and 5.3451 for example. It was just creating bigger animations than necessary and causing a lot of int16 overflows with animations with more keyframes or bones.
> Fix AnbMaker interpolation and rounding. (Smaller animations)

- OpenKh.Patcher/Metadata.cs
- OpenKh.Patcher/PatcherProcessor.cs
- OpenKh.Tools.ModsManager/Exceptions/Exceptions.cs
- OpenKh.Tools.ModsManager/Services/ConfigurationService.cs
- OpenKh.Tools.ModsManager/Services/ModsService.cs
- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
- OpenKh.Tools.ModsManager/ViewModels/ModViewModel.cs
Adds definitions to the mod.yml file for the following fields:
- isCollection: boolean for if the specific mod install is actually a collection (ie contains multiple games worth of info)
- collectionGames: string list of the games that have mods included
- asset.game: string to specify which game the script belongs with
This allows for the install and update of collection based mods from Github using the above tags in the mod.yml as well as the update and auto update of said installed mods. Creates a parent folder called collections on the same level as the game specific folders. And cleans up any installation of the mod that happened before it became a collection.
> Add support for Github multi game collections

- OpenKh.Command.MapGen/Utils/FlattenDoctBuilderAlt.cs
- OpenKh.Command.MapGen/Utils/MapBuilder.cs
Title.
Using the disableBSPCollisionBuilder2 option now applies a new form of DOCT generation which allows you to assign specific faces into their own rendering nodes using the "group" tag on the material of said mesh. This allows you to hide and unhide the meshes using MapVisibility flags in the ARD.
This change also now allows you to flag specific material faces with a "floorLevel" value, which the game uses for shadow rendering.
> [MapGen] Include Group & floorLevel support for DOCT files, fix disableBSPCollisionBuilder2 from not applying properly.

- OpenKh.Tools.Kh2MapStudio/MapRenderer.cs
Rotation was coming before scale, causing weird skewing issues when rotating a bounding box. It's fixed by moving scale before rotation.
> Fix: Correct matrix transform order for AABB in KH2 Map Studio

- OpenKh.Tools.ModsManager/ViewModels/MainViewModel.cs
If mod manager cannot open due to the log file being in use it will kill all processes of mod manager then restart to properly load the log file. (allowing the debug window to show up properly since that relies on the log)
> Fix mod manager not opening sometimes
